{
  "hash": "21d29984671c06b6529777eb3cfbb637",
  "result": {
    "engine": "knitr",
    "markdown": "---\npagetitle: \"Advanced Econometrics III\"\nunitcode: \"(Econometrics III)\"\nunitname: \"Advanced Econometrics III\"\nauthor: \"Hu Huaping (胡华平)\"\nemail: \"huhuaping01 at hotmail.com\"\nuniversity: \"NWAFU (西北农林科技大学)\"\ndepartment: \"School of Economics and Management (经济管理学院)\"\nsubtitle: \"Chapter 19. What is the Identification Problem ?\"\ndate: \"2024-09-25\"\n#keep-md: true\nformat: \n  revealjs: \n    footer: \"Chapter 19. What is the Identification Problem ?\"\n---\n\n\n\n## 环境准备{visibility=\"hidden\"}\n\n\n\n\n\n\n\n\n\n# 标题页 {visibility=\"hidden\"}\n\n## <br>Advanced Econometrics III{background-image=\"pic/slide-front-page.jpg\" #etc5523-title .center-h style=\"font-size:65px\" visibility=\"uncounted\"}\n\n### **(Econometrics III)**{.monash-black .center-h style=\"font-family:'sans-serif'; font-size:65px !important\"}\n\n\n### Chapter 19. What is the Identification Problem ?{.monash-blue .center-h style=\"font-size:70px !important\"}\n\n<br>\n\n#### Hu Huaping (胡华平) {.center-h .monash-black}\n\n#### huhuaping01 at hotmail.com {.center-h .monash-black style=\"font-family:'sans-serif';\"}\n\n#### School of Economics and Management (经济管理学院) {.center-h .monash-black}\n\n\n#### 2024-09-25 {.center-h .monash-black}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n# Part 2：Simultaneous Equation Models (SEM){.monash-bg-blue .mcenter visibility=\"uncounted\"}\n\n::: {.font-110}\n\nChapter 17. Endogeneity and Instrumental Variables\n\nChapter 18. Why Should We Concern SEM ?\n\n[Chapter 19. What is the Identification Problem ?]{.red}\n\nChapter 20. How to Estimate SEM ?\n\n:::\n\n\n\n\n# Chapter 19. What is the Identification Problem ?{#chpt19 .monash-bg-blue .mcenter}\n\n\n::: {.font-110}\n\n[19.1 Identification Problem](#deninition)\n\n[19.2 Identification Rules](#rules)\n\n[19.3 Endogeneity Test](#test-endogeneity)\n\n[19.4 Exogeneity Test](#test-exogeneity)\n\n:::\n\n\n\n::: {.notes}\nIn this chapter, we will explain the identification problems with simultaneous equation model.\n:::\n\n\n# 19.1 Identification Problem{#definition .monash-bg-blue .mcenter}\n\n::: {.notes}\nFirstly, I will show the some intuitive demonstration for the identification, and give some important notations.\n:::\n\n\n## Identification problem of SEM\n\nThe **identification problem** means whether numerical estimates of the **structural parameters**  can be obtained from the estimated **reduced coefﬁcients**.\n\n**Identification status**:\n\n- If the estimator of structural parameter can be obtained, the equation is said to be **Identified**, and there may be two district situations:\n\n- **Just/Exact Identiﬁcation**: The unique estimator of the structure parameter can be obtained.\n- **Overidentiﬁcation**: More than one estimator of a structural parameter can be obtained.\n\n- If the estimator of structural parameter cannot be obtained, the particular equation is said to be **Underidentiﬁcation**.\n\n::: {.notes}\nThe most important thing we should concern is the solution of the SEM.And this is what we call the identification problems of SEM.___We sholud know three types identification situations.\n:::\n\n\n## Example\n\n<!-- insert image here -->\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n##\n\n### The structural SEM\n\nConsider the following SEM for supply and demand:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ &= \\alpha_0+\\alpha_1P_t+u_{t1}   &(\\alpha_1<0)  &&\\text{(demand function)}\\\\\nQ &= \\beta_0+\\beta_1P_t+u_{t2}  &(\\beta_1>0) &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\n::: {.notes}\nHere, we will give an origin SEM for simple supply and demand system.\n:::\n\n##\n\n### Scatter plots\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Scatter of Q and P](images/lecture-19-sem-identification.rmarkdown/fig-plot1-scatter-1.png){#fig-plot1-scatter fig-align='center' width=960}\n:::\n:::\n\n\n\n::: {.notes}\nThis figure gives a few scatterpoints relating Q to P\n:::\n\n\n##\n\n### Equilibrium point of supply and demand\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Each scatter represents the intersection of a demand curve and a supply curve.](images/lecture-19-sem-identification.rmarkdown/fig-plot2-inter-1.png){#fig-plot2-inter fig-align='center' width=960}\n:::\n:::\n\n\n\n::: {.notes}\nEach scatterpoint represents the intersection of a demand and a supply curve, as shown in this Figure.\n:::\n\n##\n\n### Underidentification\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/lecture-19-sem-identification.rmarkdown/plot3-both-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\nWe can't be sure which of the entire family of supply and demand curves is responsible for this point. thus the supply and demand equation are both **underidentification**.\n\n\n::: {.notes}\nNow consider a single point, such as that shown in this Figure.There is no way we can be sure which demand-and-supply curve of a whole family of curves shown in that panel generated that point.___Clearly, some additional information about the nature of the demand-and-supply curves isneeded.\n:::\n\n##\n\n### The supply curve can be identified\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/lecture-19-sem-identification.rmarkdown/plot4-demand-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\nIf the demand curve shifts over time due to changes in income, tastes, etc., and the supply curve remains relatively stable, the scatter will show a **Supply Curve**. In this case, we say that the supply curve is **Exact Identiﬁcation**.\n\n::: {.notes}\netc.(/ˌet ˈsetərə; ˌɪt ˈsetərə/)\n:::\n\n\n##\n\n### The demand curve can be identified\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/lecture-19-sem-identification.rmarkdown/plot5-supply-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\nIf the supply curve shifs over time due to changes in climatic conditions or other external factors, but the demand curve remains relatively stable, the scatter will show a **demand curve**. In this case, we say that the demand curve is **identified**.\n\n::: {.notes}\nclimatic(/klaɪˈmætɪk/)By the same token, if the supply curve shifts over time because of changes in weather conditions (in the case of agricultural commodities) or other extraneous(/ɪkˈstreɪniəs/) factors but the demand curve remains relatively stable, as in this Figure, the scatterpoints trace out a demand curve.In this case, we say that the demand curve is identiﬁed.\n:::\n\n\n## Under identification\n\n<!-- insert image here -->\n\n##\n\n### Structural and reduced SEM\n\nGive the Structural SEM:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_t &= \\alpha_0+\\alpha_1P_t+u_{t1}   &(\\alpha_1<0)  &&\\text{(demand function)}\\\\\nQ_t &= \\beta_0+\\beta_1P_t+u_{t2}  &(\\beta_1>0) &&\\text{(supply function)}\\\\\n\\end{align}\n\\end{cases}\n$$\n\n\n> It's easy to obtain the Reduced SEM:\n\n$$\n\\begin{cases}\n\\begin{align}\nP_t &= \\pi_{11} +v_{t1}  \\\\\nQ_t &= \\pi_{12} +v_{t2}\n\\end{align}\n\\end{cases}\n$$\n\n::: {.callout-note}\nObviously, the structural SEM is **underidentification**! (Why?)\n\n- number of structural parameters? 2\n\n- number of reduced parameters? 0\n\n:::\n\n::: {.notes}\nSo, Let's give more details about the identification problem of SEM.Firstly, we will analyse the situation of under identification.___The reason we could not identify the demand function or the supply equation was that the same variables P and Q are present in both equations and there is no additional information.And this problem was explained in our graph demostration as what we have mentioned before.\n:::\n\n##\n\n### An made-up \"hybrid\" equation\n\n<!-- For the structural SEM, we can transform to: -->\n\n$$\n\\begin{cases}\n\\begin{align}\n\\lambda Q &= \\lambda\\alpha_0+\\lambda\\alpha_1P_t+\\lambda u_{t1}  &(\\alpha_1<0)  \\text{(transformation 1)}\\\\\n(1-\\lambda)Q &= (1-\\lambda)\\beta_0+(1-\\lambda)\\beta_1P_t+(1-\\lambda)u_{t2}  &(\\beta_1>0) \\text{(transformation 2)}\n\\end{align}\n\\end{cases}\n$$\n\nFurther, we can construct the following \"hybrid\" equation:\n\n$$\n\\begin{align}\nQ_t &= \\lambda\\alpha_0+(1-\\lambda)\\beta_0 +(\\lambda\\alpha_1+(1-\\lambda)\\beta_1 )P_t+ \\lambda u_{1t}+(1-\\lambda)u_{t2}  & \\text{(hybrid equation)} \\\\\n\\end{align}\n$$\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n\nAnd denoted as:\n\n$$\n\\begin{align}\nQ_t &= \\gamma_0 +\\gamma_1P_t+w_t   \\\\\n\\end{align}\n$$\n\n:::\n\n::: {.column width=\"15%\"}\n\n:::\n\n\n::: {.column width=\"40%\"}\n\n\nWhere:\n\n$$\n\\begin{cases}\n\\begin{align}\n\\gamma_0 & = \\lambda\\alpha_0+(1-\\lambda)\\beta_0 \\\\\n\\gamma_1 &= \\lambda\\alpha_1+(1-\\lambda)\\beta_1  \\\\\nw_t &= \\lambda u_{1t}+(1-\\lambda)u_{t2}\n\\end{align}\n\\end{cases}\n$$\n\n:::\n\n::::\n\n\n- This **hybrid equation** is indistinguishable from any of the structural equations!\n\n- So the original structural SEM is **underidentification**!\n\n::: {.notes}\n- 该虚构的**混杂方程**与结构方程中的任何一个都是无差异的！- 因此表明原来的结构方程是**不可识别的**！\n:::\n\n\n## Just identification\n\n<!-- insert image here -->\n\n##\n\n### Structural and reduced SEM\n\nGiven **Structural**  SEM (  $I=$  income of the consumer):\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_t &= \\alpha_0+\\alpha_1P_t+\\alpha_2I_t+u_{t1}   &(\\alpha_1<0,\\alpha_2>0)  &&\\text{(demand function)}\\\\\nQ_t &= \\beta_0+\\beta_1P_t+u_{t2}  &(\\beta_1>0) &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\nWe can obtain the **Reduced** SEM:\n\n$$\n\\begin{cases}\n\\begin{align}\nP_t &= \\pi_{11}+ \\pi_{21}I_t+v_{t1} \\\\\nQ_t &= \\pi_{12}+ \\pi_{22}I_t+v_{t2}\\\\\n\\end{align}\n\\end{cases}\n$$\n\n\n$$\n\\begin{cases}\n\\begin{alignedat}{3}\n& \\pi_{11} = \\frac{\\beta_0-\\alpha_0}{\\alpha_1-\\beta_1}; \\quad\n& \\pi_{21} = - \\frac{\\alpha_2}{\\alpha_1-\\beta_1} ; \\quad\n& v_{t1} = \\frac{u_{t2}-u_{t1}}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{12} = \\frac{\\alpha_1\\beta_0-\\alpha_0\\beta_1}{\\alpha_1-\\beta_1};\\quad\n& \\pi_{22} = - \\frac{\\alpha_2\\beta_1}{\\alpha_1-\\beta_1} ;\\quad\n& v_{t2} = \\frac{\\alpha_1u_{t2}-\\beta_1u_{t1}}{\\alpha_1-\\beta_1}\n\\end{alignedat}\n\\end{cases}\n$$\n\n::: {.notes}\nBut suppose we consider the following demand-and-supply model, where  $I =$ income of the consumer, an exogenous variable, and all other variables are as deﬁned previously.Notice that the only difference between this structural SEM and our prementioned original demand-and-supply model is that there is an additional variable in the demand function, namely, income.From economic theory of demand we know that income is usually an important determinant of demand for most goods and services.Therefore, its inclusion in the demand function will give us some additional information about consumer behavior.\n:::\n\n\n##\n\n### Part equation just-identified\n\n:::: {.callout-note}\n\n[**Question**]{.red}：\n\nCan the aforementioned structural equation be identified?\n\n- number of reduced parameters?\n- number of structural parameters?\n\n**Answer**：\n\n::: {.fragment}\n\n- Only 4 reduced parameters:  $\\pi_{11},\\pi_{21},\\pi_{12},\\pi_{22}$\n\n- But 5 structural parameters:  $\\alpha_0,\\alpha_1,\\alpha_2,\\beta_0,\\beta_1$ \n\n:::\n\n::::\n\n\nTherefore, it is impossible to completely solve all 5 structural parameters.\n\n\nHowever, the **supply equation** is **Exact identification**, because:\n\n$$\n\\begin{align}\n\\beta_0 = \\pi_{12}-\\beta_1\\pi_{11} ; \\quad\n\\beta_1 = \\frac{\\pi_{22}}{\\pi_{21}}\n\\end{align}\n$$\n\nBut there is no unique way of estimating the parameters of the **demand function**.\n\nTherefore, the **demand equation** remains underidentified.\n\n::: {.notes}\nBut there is no unique way of estimating the parameters of the **demand function**.Therefore, the **demand equation** remains underidentified.\n:::\n\n\n##\n\n### Structural SEM\n\nGiven **Structural**  SEM (  $P_{t-1}=$  price lagged one period):\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_t &= \\alpha_0+\\alpha_1P_t+\\alpha_2I_t+u_{t1}   &(\\alpha_1<0,\\alpha_2>0)  &&\\text{(demand function)}\\\\\nQ_t &= \\beta_0+\\beta_1P_t+ \\beta_2P_{t-1}+u_{t2}  &(\\beta_1>0,\\beta_2>0) &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\n::: {callout-note}\n\nwhere the demand function remains as before but the supply function includes an additional explanatory variable, price lagged one period.\n\n:::\n\n::: {.notes}\nThe supply function postulates that the quantity of a commodity supplied depends on its current and previous period’s price.Note that  $P_{t−1}$  is a predetermined variable because its value is known at time t.\n:::\n\n##\n\n### Reduced SEM\n\nWe can obtain the **Reduced** SEM:\n\n$$\n\\begin{cases}\n\\begin{align}\nP_t &= \\pi_{11}+ \\pi_{21}I_t + \\pi_{31}P_{t-1} +v_{t1} \\\\\nQ_t &= \\pi_{12}+ \\pi_{22}I_t + \\pi_{32}P_{t-1} +v_{t2}\\\\\n\\end{align}\n\\end{cases}\n$$\n\nAnd obtain the relationship between the structural coefficients and the reduced coefficients.\n\n::: {.font-90}\n\n$$\n\\begin{cases}\n\\begin{alignedat}{3}\n& \\pi_{11} = \\frac{\\beta_0-\\alpha_0}{\\alpha_1-\\beta_1}; \\quad\n& \\pi_{21} = - \\frac{\\alpha_2}{\\alpha_1-\\beta_1} ; \\quad\n& \\pi_{31} = - \\frac{\\beta_2}{\\alpha_1-\\beta_1} ; \\quad\n& v_{t1} = \\frac{u_{t2}-u_{t1}}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{12} = \\frac{\\alpha_1\\beta_0-\\alpha_0\\beta_1}{\\alpha_1-\\beta_1};\\quad\n& \\pi_{22} = - \\frac{\\alpha_2\\beta_1}{\\alpha_1-\\beta_1} ;\\quad\n& \\pi_{32} =  \\frac{\\alpha_1\\beta_2}{\\alpha_1-\\beta_1} ;\\quad\n& v_{t2} = \\frac{\\alpha_1u_{t2}-\\beta_1u_{t1}}{\\alpha_1-\\beta_1}\n\\end{alignedat}\n\\end{cases}\n$$\n\n:::\n\n\n::: {.callout-tip}\nSo, can we calculate the unique structural coefficients by using the numerical reduced coefficients?\n:::\n\n::: {.notes}\nas what we have done before, let's count the parameters for structural SEM and reduced SEM  firstly.\n:::\n\n\n##\n\n### All equations just-identified\n\n:::: {.callout-note}\n\n\n[**Question**]{.red}：\n\nCan the aforementioned structural equation be identified?\n\n- number of reduced parameters?\n\n- number of structural parameters?\n\n\n**Answer**：\n\n::: {.fragment}\n\n- there are 6 reduced parameters:  $\\pi_{11},\\pi_{21},\\pi_{31};\\pi_{12},\\pi_{22},\\pi_{32}$\n\n- and 6 structural parameters:  $\\alpha_0,\\alpha_1,\\alpha_2;\\beta_0,\\beta_1,\\beta_2$ \n\n:::\n\n::::\n\nTherefore, the parameters of both the SEM equations can be identiﬁed, and the system as a whole can be  identiﬁed exactly.\n\n\n\n::: {.notes}\nNotice an interesting fact: It is the presence of an additional variable in the demand function that enables us to identify the supply function! Why?As will be shown shortly, very often the identifiability of an equation depends on whether it **excludes** one or more variables that are **included** in other equations in the model.\n:::\n\n\n## Over-identification\n\n<!-- insert image here -->\n\n##\n\n### Structural SEM\n\nNow suppose we consider the following structural SEM for demand-and-supply:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_t &= \\alpha_0+\\alpha_1P_t+\\alpha_2I_t+\\alpha_3R_t+u_{t1} &(\\alpha_1<0,\\alpha_2>0)  &&\\text{(demand function)}\\\\\nQ_t &= \\beta_0+\\beta_1P_t+\\beta_2P_{t-1}+u_{t2}   &(\\beta_1,\\beta_2>0) &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\nWhere the supply function remains as before but the demand function includes two additional explanatory variables, **income**(  $I_{t}$ ) and **wealth**(  $R_t$ ).\n\n<br>\n\n> [**Questions**]{.red}：Can you transform the structural SEM to get the reduced SEM?\n\n::: {.notes}\nFor most goods and services, like wealth and income, are expected to have a positive effect on consumption.Note  **income**(  $I_{t}$ ) and **wealth**(  $R_t$ ) are supposed to be exogenous variables.\n:::\n\n\n##\n\n### Reduced SEM\n\nWe can get the reduced SEM and the relationship between Structural and reduced pars:\n\n$$\n\\begin{cases}\n\\begin{align}\nP_t &= \\pi_{11}+ \\pi_{21}I_t+\\pi_{31}R_t+\\pi_{41}P_{t-1}+v_{t1} \\\\\nQ_t &= \\pi_{12}+\\pi_{22}I_t+\\pi_{32}R_t+\\pi_{42}P_{t-1}+v_{t2}\n\\end{align}\n\\end{cases}\n$$\n\n\n:::: {.columns}\n\n::: {.column width=\"40%\" .font-95}\n\n\n$$\n\\begin{cases}\n\\begin{align}\n& \\pi_{11} = \\frac{\\beta_0-\\alpha_0}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{21} = - \\frac{\\alpha_2}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{31} = - \\frac{\\alpha_3}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{41} = \\frac{\\beta_2}{\\alpha_1-\\beta_1} \\\\\n& v_{t1} = \\frac{u_{t2}-u_{t1}}{\\alpha_1-\\beta_1}\n\\end{align}\n\\end{cases}\n$$\n\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n\n::: {.column width=\"40%\" .font-95}\n\n\n$$\n\\begin{cases}\n\\begin{align}\n& \\pi_{12} = - \\frac{\\alpha_1\\beta_0-\\alpha_0\\beta_1}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{22} = - \\frac{\\alpha_2\\beta_1}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{32} = - \\frac{\\alpha_3\\beta_1}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{42} =   \\frac{\\alpha_1\\beta_2}{\\alpha_1-\\beta_1} \\\\\n&v_{t2} = \\frac{\\alpha_1u_{t2}-\\beta_1u_{t1}}{\\alpha_1-\\beta_1}\n\\end{align}\n\\end{cases}\n$$\n\n:::\n\n::::\n\n\n##\n\n### Multiple solutions\n\n:::: {.callout-note}\n\n[**Questions**]{.red}：\n\nCan the Structural SEM be identified?\n\n- number of reduced parameters?\n\n- number of structural parameters?\n\n**Answer**:\n\n::: {.fragment}\n\n- 8 **Reduced parameters** :  $\\pi_{11},\\pi_{12},\\pi_{13},\\pi_{14},\\pi_{21},\\pi_{22},\\pi_{23},\\pi_{24}$\n\n- Only 7 **structural Parameters** :  $\\alpha_0,\\alpha_1,\\alpha_2,\\alpha_3,\\beta_0,\\beta_1,\\beta_2$ \n\n:::\n\n::::\n\n\nTherefore, the number of equations is more than the number of unknown coefficients, so the unique estimation value of all 7 structural coefficients cannot be obtained.\n\n> **Conclusion**: there are many solutions to the structural SEM that satisfy the condition. So it is **Overidentification**.\n\n\n# 19.2 Identification rules{#rules .monash-bg-blue .mcenter}\n\n::: {.notes}\nIn this section, we will introduce two type identification rules, which are order rules and rank rules respectively.\n:::\n\n\n## Symbols and notations\n\nFirstly, let us define the notation for the number of **variables** in the **Structural SEM**.\n\n-  $M=$ \nThe number of all **endogenous variables** in the structural SEM.\n\n-  $K=$ \nThe number of all **predetermined variables** in the structural SEM (including the intercept term)\n\n-  $m=$ \nThe number of endogenous variables in a particular equation.\n\n-  $k=$ \nThe number of **predeterminate variables** in a particular equation (including the intercept term).\n\n::: {.notes}\nupper case Mlower case mSo it should  be different for upper case and lower case.Also, you should remind the upper K and lower k both contain the intercept term.\n:::\n\n## The order rules\n\n<!-- insert image here -->\n\n##\n\n### Solution 1\n\nA necessary (but not sufﬁcient) condition of identification, known as the **order condition**, may be stated in two different but equivalent ways.\n\n::: {.callout-tip title=\"Order rules 1\" .font-115}\n\nIn a model of M simultaneous equations, in order for an equation to be identiﬁed, it must exclude at least  $M − 1$  variables (endogenous as well as predetermined) appearing in the SEM.\n\n- If it excludes exactly  $M − 1$  variables, the equation is **just identiﬁed**. Which means  $M+K-(k+m) = (M-1)$ .\n\n- If it excludes more than  $M − 1$  variables, it is **overidentiﬁed**. Which means  $M+K-(k+m) > (M-1)$ \n\n:::\n\n##\n\n### Solution 2\n\nAnd here is another equivalent order rule.\n\n::: {.callout-tip title=\"Order rules 2\" .font-115}\n\nIn a model of M simultaneous equations, in order for an equation to be identiﬁed, the number of predetermined variables( $k$ ) excluded from the equation must not be less than the number of endogenous variables(  $m$ ) included in that equation less 1, that is,\n\n- If $K − k = m − 1$, the equation is **just identiﬁed**.\n\n- but if $K − k > m − 1$, it is **overidentiﬁed**.\n\n:::\n\n\n## Case demo\n\n<!-- insert image here -->\n\n##\n\n### Both under-identification\n\nThe **structural SEM** is:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_t &= \\alpha_0+\\alpha_1P_t+u_{t1}   &(\\alpha_1<0)  &&\\text{(demand function)}\\\\\nQ_t &= \\beta_0+\\beta_1P_t+u_{t2}  &(\\beta_1>0) &&\\text{(supply function)}\\\\\n\\end{align}\n\\end{cases}\n$$\n<br>\n\n::: {.callout-tip title=\"Conclusion from **Order Rule 1**\" .font-115}\n\n- All numbers of variables in the structural SEM is  $(M+K)=2+0=2$ , and  $(M-1)=2-1=1$ .\n\n- For the first equation, because number of all variables is  $(m + k) = 2 + 0 = 2$ , so  $(M + K) - (m + k) = 2-2 = 0$ . We see  $(M + K) - (m + k) < (M - 1)=1$ . So the first equation (the demand equation) is **Underidentification**.\n\n- For the second equation, because  $(m + k) = 2 + 0 = 2$ , so $(M + K) - (m + k) = 2-2 = 0$. We see  $(M + K) - (m + k) < (M - 1)=1$ . So the second equation (the supply equation) is also **Underidentification**\n\n:::\n\n::: {.notes}\nFor simplicity, order rule 1 means that numbers of excluded variables in the particular equation is less than the numbers of all endogenous variables minus 1 in the SEM, and this means the particular equation is under-identification.\n:::\n\n##\n\n### Both under-identification\n\nThe **structural SEM** is:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_t &= \\alpha_0+\\alpha_1P_t+u_{t1}   &(\\alpha_1<0)  &&\\text{(demand function)}\\\\\nQ_t &= \\beta_0+\\beta_1P_t+u_{t2}  &(\\beta_1>0) &&\\text{(supply function)}\\\\\n\\end{align}\n\\end{cases}\n$$\n<br>\n\n::: {.callout-tip title=\"Conclusion from **Order Rule 2**\" .font-115}\n\n- The number of predetermined variables in the structural SEM is  $K=1$ .\n\n- For the **first** equation: the number of predetermined variables is  $k=0$ , and  $(K -k)=0$ ; The number of endogenous variables is $m=2$, and  $(m-1)=1$ ; We see  $(K-k) < (m - 1)$ . So the first equation (the demand equation) is **Underidentification**.\n\n- For the **second** equation: the number of predetermined variables is  $k=0$ , and  $(K -k)=0$ ; The number of endogenous variables is  $m=2$ , and  $(m-1)=1$ ; We see  $(K-k) < (m - 1)$ . So the second equation (the supply equation) is also **Underidentification**.\n\n:::\n\n\n::: {.notes}\nFor simplicity, order rule 2 imply that numbers of excluded predetermined variables in the particular equation is less than the numbers of its include endogenous variables minus 1, which means the particular equation is under-identification.\n:::\n\n##\n\n### (Under + Just) identification\n\nThe **structural SEM** is:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_t &= \\alpha_0+\\alpha_1P_t+\\alpha_2I_t+u_{t1}   &(\\alpha_1<0,\\alpha_2>0)  &&\\text{(demand function)}\\\\\nQ_t &= \\beta_0+\\beta_1P_t+u_{t2}  &(\\beta_1>0) &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\n<br>\n\n::: {.callout-tip title=\"Conclusion from **Order Rule 1**\" .font-115}\n\n\n- In the structural SEM: The number of all variables is  $(M+K)=2+1=3$ , and  $(M-1)=2-1=1$ .\n\n- The first eq: the number of all variables is  $(m + k) = 2 + 1 = 3$ , so  $(M + K) - (m + k) = 3-3 = 0$ . We see  $(M + K) - (m + k) < (M-1)=1$ . Thus the first equation is **Underidentification**.\n\n- The second eq: the number of all variables is  $(m + k) = 2 + 0 = 2$ , so  $(M + K) - (m + k) = 3-2= 1$ . We see  $(M +K) - (m + k) = (M - 1)=1$ . Thus the second equation is **Just identification**.\n\n:::\n\n##\n\n### (Under + Just) identification\n\n\nThe **structural SEM** is:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_t &= \\alpha_0+\\alpha_1P_t+\\alpha_2I_t+u_{t1}   &(\\alpha_1<0,\\alpha_2>0)  &&\\text{(demand function)}\\\\\nQ_t &= \\beta_0+\\beta_1P_t+u_{t2}  &(\\beta_1>0) &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\n<br>\n\n::: {.callout-tip title=\"Conclusion from **Order Rule 2**\" .font-115}\n\n\n- The number of  predetermined variables in the structural SEM is  $K=2$ \n\n- For the first equation: The number of predetermined variables is  $k=1$ , and  $(K -k)=0$ ; The number of endogenous variables is  $m=2$ , and  $(m-1)=1$ ; Obviously  $(K - k) < (m - 1)=1$ . So the first equation (the demand equation) is **Underidentification**.\n\n- For the second equation: the number of  predetermined variables is  $k=0$ , and  $(K -k)=1$ ; The number of endogenous variables is  $m=2$ , and  $(m-1)=1$ ; Obviously  $(K - k) = (m - 1)=1$ . So the second equation (supply equation) is **Just identification**.\n\n:::\n\n##\n\n### (Just + Over) identification\n\n\nThe **structural SEM** is:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_t &= \\alpha_0+\\alpha_1P_t+\\alpha_2I_t+\\alpha_3R_t+u_{t1} &(\\alpha_1<0,\\alpha_2>0)  &&\\text{(demand function)}\\\\\nQ_t &= \\beta_0+\\beta_1P_t+\\beta_2P_{t-1}+u_{t2}   &(\\beta_1,\\beta_2>0) &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\n<br>\n\n::: {.callout-tip title=\"Conclusion from **Order Rule 1**\" .font-115}\n\n- In this structural SEM: the number of all variables is  $(M+K)=2+3=5$ , and  $(M-1)=2-1=1$ \n\n- The first equation: the number of all variables is  $(m + k) = 2 + 3 = 5$ , so  $(M + K) - (m + k) =  5-4= 1$ . We see clearly  $(M + K) - (m + k) = (M - 1)=1$ . Hence the first equation is **Just Identification**\n\n- The second equation: the number of all variables is  $(m + k) = 2 + 1 = 3$ , so  that  $(M + K) - (m + k) = 5-3 = 2$ . We see  $(M + K) - (m + k) > (M - 1)=1$ . Thus, the second equation is **Overidentification**\n\n:::\n\n\n##\n\n### (Just + Over) identification\n\n\nThe **structural SEM** is:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_t &= \\alpha_0+\\alpha_1P_t+\\alpha_2I_t+\\alpha_3R_t+u_{t1} &(\\alpha_1<0,\\alpha_2>0)  &&\\text{(demand function)}\\\\\nQ_t &= \\beta_0+\\beta_1P_t+\\beta_2P_{t-1}+u_{t2}   &(\\beta_1,\\beta_2>0) &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\n\n<br>\n\n::: {.callout-tip title=\"Conclusion from **Order Rule 2**\" .font-115}\n\n- In the structural SEM: The number of predetermined variables  $K=3$ .\n\n- The first equation: the number of predetermined variables  $k=2$ , and  $(K -k)=1$ ; The number of endogenous variables is  $m=2$ , and  $(m-1)=1$ ; We see  $(K - k) = (m - 1)=1$ . So the first equation  is the **Just Identification**.\n\n- The second equation: the number of predetermined variables is  $k=1$ , and  $(K -k)=2$ ; The number of endogenous variables is  $m=2$ , and  $(m-1)=1$ ; We see  $(K - K) > (m - 1)=1$ . So the second equation  is **overidentification**.\n\n:::\n\n##\n\n### Conclusion of order rules (1/2)\n\n- Firstly, the order rule is a **necessary** but not **sufficient** condition  for Identificatoin problems. Thus even if order conditions are satisfied, the equation will be unidentifiable.\n\n\n::: {.callout-note title=\"Example\" .font-115}\n\n\n$$\n\\begin{cases}\n\\begin{align}\nQ &= \\alpha_0+\\alpha_1P_t+\\alpha_2I_t+u_{t1}   &(\\alpha_1<0,\\alpha_2>0)  &&\\text{(demand function)}\\\\\nQ &= \\beta_0+\\beta_1P_t+u_{t2}  &(\\beta_1>0) &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\n\n- According to the rules of order conditions, we can judge that the second equation (the supply equation) is **Just Identification**.\n\n- In fact, we also need to make sure that the coefficient of income variable  $I_t$  in the first equation should satisfy  $\\alpha_2 \\neq 0$ .\n\n- But notice that the zero restrictions criterion is based on a priori or theoretical expectations that certain variables do not appear in a given equation.\n\n:::\n\n::: {.notes}\nSo, let's sum up the discussion about the rules of order condition.\n:::\n\n##\n\n### Conclusion of order rules (2/2)\n\n- Secondly, **Order Rule 1** and **Order Rule 2** are equivalent.\n\n- Finally, it's only suitable for the simple SEM situatons to use the Rule of Order Condition.\n\n::: {.notes}\n-  The practical rule of thumb that every equation have at least one variable in it that does not appear in any other equation will guarantee this outcome.\n\n$$\n\\begin{align}(M+K)-(m+k) &> M-1 \\\\\n(M+K)-(m+k) &> M-1 \\\\\nK-k & > m-1\n\\end{align}\n$$\n\n:::\n\n\n## The Rank Rules\n\n<!-- insert image here -->\n\n##\n\n### Rank Rules and the Main procedure\n\n::: {.callout-note title=\"The Rank Rules\" .font-115}\n\nIn a model containing M equations in M endogenous variables, an equation is identiﬁed if and only if at least one non-zero determinant of order  $(M − 1)\\times(M − 1)$  can be constructed from the coefﬁcients of the variables (both endogenous and predetermined) excluded from that particular equation but included in the other equations of the model.\n\n:::\n\nHere are the **Main proceeding steps**:\n\n1. Transform the structural SEM and write down the **algebraic formula 2**.\n\n2. Write the corresponding table of **equation coefficients**.\n\n3. Find all **columns** that are not included in the equation.\n\n4. Construct any  $(M - 1) \\ast (M - 1)$  matrix among these columns.\n\n5. Judge and draw a conclusion: if any matrix with a determinant of 0 can be found, the equation is **underidentification**.\n\n::: {.notes}\nSo, you may ask that what is the  **sufficient and necessary** condition for identification problem?Now, let me show you the answer here.___The rank rules seems be confused and tedious.And I will give you an examle in the next few slides.- 在一个包含M个内生变量的M个方程的联立模型中，一个方程可识别的**充分必要**条件是，我们能从模型所含而该方程所不含的（内生或前定）变量系数矩阵中构造出**至少**1个  $(M-1)\\ast(M-1)$ 阶的非零行列式来。**主要操作步骤**：1. 把结构模型移项，写出**代数式2**2. 按方程写出对应的**系数列表**3. 找到该方程不含的所有**列**4. 从这些列中随意找出1个  $(M-1)\\ast(M-1)$ 的矩阵5. 判断并得出结论：如果能找到任何1个行列式为0的矩阵，则该方程就是**不可识别的**\n:::\n\n##\n\n### Step 1: fill table form of coefficients\n\n$$\n\\begin{cases}\n\\begin{alignedat}{9}\n&  Y_{t1} &-\\gamma_{21}Y_{t2}&-\\gamma_{31}Y_{t3} & &-\\beta_{01}&-\\beta_{11}X_{t1} &  & &= &u_{t1} \\\\\n& & Y_{t2} &-\\gamma_{32} Y_{3t} & & -\\beta_{02}&-\\beta_{12}X_{1t} &- \\beta_{22}X_{2t} & &= &u_{t2}\\\\\n&-\\gamma_{13}Y_{t1} &  &+ Y_{t3} & & -\\beta_{03}&-\\beta_{13}X_{1t} &-\\beta_{23}X_{2t} & &= &u_{t3} \\\\\n&-\\gamma_{14}Y_{t1}&-\\gamma_{24}Y_{t2} &  &+Y_{t4}   &-\\beta_{04} & & &-\\beta_{34}X_{t3} &= &u_{t4}\n\\end{alignedat}\n\\end{cases}\n$$\n\n\nThe parameters of the structural SEM can be written as follows:\n\n$$\n\\begin{matrix}\n--   & --  & --  & --  & --  &  --& --  & --  & --  \\\\\neq   & Y_1 & Y_2 & Y_3 & Y_4 &   1& X_1 & X_2 & X_3 \\\\\n--   &  -- & --  & --  & --  & -- & --  & --  & --  \\\\\n1   & 1 & -\\gamma_{21} & -\\gamma_{31} & 0 & -\\beta_{01}& -\\beta_{11} & 0 & 0 \\\\\n2   & 0 & 1 & -\\gamma_{32} & 0 & -\\beta_{02}& -\\beta_{12} & -\\beta_{22} & 0 \\\\\n3   & -\\gamma_{13} & 0 & 1 & 0 & -\\beta_{03}& -\\beta_{13} & -\\beta_{23} & 0 \\\\\n4   & -\\gamma_{14} & -\\gamma_{24} & 0 & 1 & -\\beta_{04}& 0 & 0 & -\\beta_{34} \\\\\n\\end{matrix}\n$$\n\n::: {.notes}\nNow, let me show you an example.___this slide shows the firs two steps:1. Transform the structural SEM and write down the **algebraic formula 2**.2. Write the corresponding table of **equation coefficients**.\n:::\n\n##\n\n### Step 2: check variables and column\n\n\n$$\n\\begin{cases}\n\\begin{alignedat}{9}\n&  Y_{t1} &-\\gamma_{21}Y_{t2}&-\\gamma_{31}Y_{t3} & &-\\beta_{01}&-\\beta_{11}X_{t1} &  & &= &u_{t1} \\\\\n& & Y_{t2} &-\\gamma_{32} Y_{3t} & & -\\beta_{02}&-\\beta_{12}X_{1t} &- \\beta_{22}X_{2t} & &= &u_{t2}\\\\\n&-\\gamma_{13}Y_{t1} &  &+ Y_{t3} & & -\\beta_{03}&-\\beta_{13}X_{1t} &-\\beta_{23}X_{2t} & &= &u_{t3} \\\\\n&-\\gamma_{14}Y_{t1}&-\\gamma_{24}Y_{t2} &  &+Y_{t4}   &-\\beta_{04} & & &-\\beta_{34}X_{t3} &= &u_{t4}\n\\end{alignedat}\n\\end{cases}\n$$\n\n- The endogenous variables not included in the first equation are:  $Y_{t4}$ ;and predetermined variables not included:  $X_{t2},X_{t3}$ .\n\n$$\n\\begin{matrix}\n--   & --  & --  & --  & --  &  --& --  & --  & --  \\\\\neq   & Y_1 & Y_2 & Y_3 & [Y_4] &   1& X_1 & [X_2] & [X_3] \\\\\n--   &  -- & --  & --  & --  & -- & --  & --  & --  \\\\\n1   & 1 & -\\gamma_{21} & -\\gamma_{31} & 0 & -\\beta_{01}& -\\beta_{11} & 0 & 0 \\\\\n2   & 0 & 1 & -\\gamma_{32} & 0 & -\\beta_{02}& -\\beta_{12} & -\\beta_{22} & 0 \\\\\n3   & -\\gamma_{13} & 0 & 1 & 0 & -\\beta_{03}& -\\beta_{13} & -\\beta_{23} & 0 \\\\\n4   & -\\gamma_{14} & -\\gamma_{24} & 0 & 1 & -\\beta_{04}& 0 & 0 & -\\beta_{34} \\\\\n\\end{matrix}\n$$\n\n::: {.notes}\nAnalyze variables in the first equation; Find the missing columnIn this slide, we will conduct the step 3:3. Find all **columns** that are not included in the equation.\n:::\n\n##\n\n### Step 3: obtain matrix determinant\n\n\n$$\n\\begin{matrix}\n--   & --  & --  & --  & --  &  --& --  & --  & --  \\\\\neq   & Y_1 & Y_2 & Y_3 & [Y_4] &   1& X_1 & [X_2] & [X_3] \\\\\n--   &  -- & --  & --  & --  & -- & --  & --  & --  \\\\\n1   & 1 & -\\gamma_{21} & -\\gamma_{31} & 0 & -\\beta_{01}& -\\beta_{11} & 0 & 0 \\\\\n2   & 0 & 1 & -\\gamma_{32} & 0 & -\\beta_{02}& -\\beta_{12} & -\\beta_{22} & 0 \\\\\n3   & -\\gamma_{13} & 0 & 1 & 0 & -\\beta_{03}& -\\beta_{13} & -\\beta_{23} & 0 \\\\\n4   & -\\gamma_{14} & -\\gamma_{24} & 0 & 1 & -\\beta_{04}& 0 & 0 & -\\beta_{34} \\\\\n\\end{matrix}\n$$\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n\n$$\n\\begin{alignat}{3}\nA=\n\\begin{bmatrix}\n0 & -\\beta_{22} &  0 \\\\\n0 & -\\beta_{32} & 0 \\\\\n1 & 0 &  -\\beta_{34} \\\\\n\\end{bmatrix}\n\\end{alignat}\n$$\n:::\n\n\n::: {.column width=\"40%\"}\n\n\n$$\n\\begin{alignat}{3}\ndet(A)=\n\\begin{vmatrix}\n0 & -\\beta_{22} &  0 \\\\\n0 & -\\beta_{32} & 0 \\\\\n1 & 0 &  -\\beta_{43} \\\\\n\\end{vmatrix}\n=0\n\\end{alignat}\n$$\n:::\n\n::::\n\nThat means the rank of the matrix  $rank(A)=\\mathbf{\\rho}(A)<3$ . \n\nTherefore, [the first equation]{.red} does not satisfy the **rank condition**, and it is **underidentification**.\n\n::: {.notes}\nTry to find 1 target matrix; Calculate its determinant.In this slide, we will conduct the step 4 and 5:In step 4. we can construct a matrix with  demension  $3 \\ast 3$  among these columns.in step 5. we can calculte the determinant of this matrix which equals to zero. And we also know the column rank of this matrix equals 3.Therefore, the first equationdoes does not satisfy the **rank condition**, and it is **underidentification**.\n:::\n\n##\n\n### Summary of rank rules (1/2)\n\nIn summary, the steps of the rank condition rules are as follows:\n\n1. Write down the **structural SEM** in the **algebra form 2**;\n\n2. Put the **coefficients** in tabular form;\n\n3. Strike out the coefﬁcients of the row in which the equation under consideration;\n\n4. Strike out the columns of the non-zero coefficients in the equation considered;\n\n5. The remaining coefficients will form a **coefficient matrix**;\n\n6. Construct arbitrary matrix with  $(M - 1)*(M - 1)$  and calculate the determinant.\n\n##\n\n### Summary of rank rules (2/2)\n\nSo, the **conclusion** of the rank rules is as follows:\n\n- If there is at least one square matrix  $(M - 1)*(M - 1)$ , with which determinant is not equal to zero (namely, the rank of the square matrix is  $m-1$ ), it will indicates that the equation under consideration is  **Just Identification**.\n\n- If determinants of all possible square matrices  $(M - 1) * (M - 1)$ are all equal to zero, which means the rank of all these square matrix is less than  $M-1$ , the equation considered is **Underidentification**.\n\n\n::: {.notes}\n.pull-left[- 把**结构方程**写成**代数式2**- 把**系数**写成表格形式- 划掉被考虑的方程所在行- 再划掉被考虑的方程中**非零系数**对应的列- 余下的系数将构成一个**系数矩阵**].pull-right[- 利用**系数矩阵**，构造任意的  $(M-1)*(M-1)$ 阶方阵，并计算方阵的行列式- 如果能找到**至少一个**行列式不等于零的  $(M-1)*(M-1)$ 阶方阵，也即该方阵的秩为M-1，则表明被考虑方程是**可识别的**（恰好或多度识别）- 如果所有可能的  $(M-1)*(M-1)$  阶方阵，它们的行列式全等于零，也即所有可能  $(M-1)*(M-1)$ 阶方阵的秩都**小于**M-1，则表明被考虑方程是**不可识别的**]\n:::\n\n\n##\n\n### Rank rule Resluts for all equations\n\n$$\n\\begin{matrix}\n--   & --  & --  & --  & --  &  --& --  & --  & --  \\\\\neq   & Y_1 & Y_2 & Y_3 & Y_4 &   1& X_1 & X_2 & X_3 \\\\\n--   &  -- & --  & --  & --  & -- & --  & --  & --  \\\\\n1   & 1 & -\\gamma_{21} & -\\gamma_{31} & 0 & -\\beta_{01}& -\\beta_{11} & 0 & 0 \\\\\n2   & 0 & 1 & -\\gamma_{32} & 0 & -\\beta_{02}& -\\beta_{12} & -\\beta_{22} & 0 \\\\\n3   & -\\gamma_{13} & 0 & 1 & 0 & -\\beta_{03}& -\\beta_{13} & -\\beta_{23} & 0 \\\\\n4   & -\\gamma_{14} & -\\gamma_{24} & 0 & 1 & -\\beta_{04}& 0 & 0 & -\\beta_{34} \\\\\n\\end{matrix}\n$$\n\n::: {.callout-tip title=\"Rank rules results:\" .font-115}\n\n- Equation 1: **underidentification**\n\n- Equation 2: ? [**underidentification**]{.fragment}\n\n- Equation 3: ? [**underidentification**]{.fragment}\n\n- Equation 4: ? [**identified**]{.fragment}\n\n:::\n\n\n::: {.notes}\nUntill now, we have know the first equation of this SEM is under-identification with the rank rules.So, what's about the other three equations?Please try to finish these process by yourself after the class.第4个是可识别的，其他都不可识别！\n:::\n\n##\n\n### Order rule Resluts for all equations\n\n$$\n\\begin{cases}\n\\begin{alignedat}{9}\n&  Y_{t1} &-\\gamma_{21}Y_{t2}&-\\gamma_{31}Y_{t3} & &-\\beta_{01}&-\\beta_{11}X_{t1} &  & &= &u_{t1} \\\\\n& & Y_{t2} &-\\gamma_{32} Y_{3t} & & -\\beta_{02}&-\\beta_{12}X_{1t} &- \\beta_{22}X_{2t} & &= &u_{t2}\\\\\n&-\\gamma_{13}Y_{t1} &  &+ Y_{t3} & & -\\beta_{03}&-\\beta_{13}X_{1t} &-\\beta_{23}X_{2t} & &= &u_{t3} \\\\\n&-\\gamma_{14}Y_{t1}&-\\gamma_{24}Y_{t2} &  &+Y_{t4}   &-\\beta_{04} & & &-\\beta_{34}X_{t3} &= &u_{t4}\n\\end{alignedat}\n\\end{cases}\n$$\n\nWith order rules 2, you should obtain following conclusion for all 4 equation:\n\n<br>\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-3e23b21d0982a5de2639\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3e23b21d0982a5de2639\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\"],[1,2,3,4],[3,2,2,3],[2,3,3,2],[4,4,4,4],[4,4,4,4],[2,1,1,2],[2,1,1,2],[\"just identification\",\"just identification\",\"just identification\",\"just identification\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>eq<\\/th>\\n      <th>m<\\/th>\\n      <th>k<\\/th>\\n      <th>M<\\/th>\\n      <th>K<\\/th>\\n      <th>K-k<\\/th>\\n      <th>m-1<\\/th>\\n      <th>result<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":6,\"rownames\":false,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"eq\",\"targets\":1},{\"name\":\"m\",\"targets\":2},{\"name\":\"k\",\"targets\":3},{\"name\":\"M\",\"targets\":4},{\"name\":\"K\",\"targets\":5},{\"name\":\"K-k\",\"targets\":6},{\"name\":\"m-1\",\"targets\":7},{\"name\":\"result\",\"targets\":8}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[6,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: {.notes}\nSo far we know that the order rules is a necessary but not sufficient condition for identification, while the rank rules is necessary and sufficient conditon for identification.So you may ask whether the results from the order rules will be the same with results from the rank rules?___This table gives the result from the order rules 2.It shows that all equations are just-identification which is differnt with the results from the rank rules.\n:::\n\n##\n\n### Summary on identification rules\n\nThe following is a comprehensive summary of the identification rules:\n\n- The order condition is a necessary but not sufficient condition for the identification ploblem, and even if it is satisfied, the equation still may be unidentifiable.\n\n- The rank condition is the **sufficient and necessary conditions** for identification problem.\n\n- Rank rules  can tell us that the if the equations is identifible or unidentifiable. While the order rules conditions will tell us if it is **just identification** or **over identification**.\n\n- Strictly, we need to first analyze the rank rules to determine whether the equation is identifiable; And then use the order rules to judge if it is **just identification** or **over identification**.\n\n::: {.notes}\nAs the preceding discussion shows, the rank condition tells us whether the equation under consideration is identiﬁed or not, while the order condition tells us if it is exactly identified or overidentified.Fortunately, the order condition is usually sufﬁcient to ensure identiﬁability, and although it is important to be aware of the rank condition, a failure to verify it will rarely result in disaster.\n:::\n\n\n# 19.3 Endogeneity test (Test of Simultaneity) $^{\\ast}$ {#test-endogeneity .monash-bg-blue .mcenter}\n\n\n::: {.notes}\nThe next two section discuss endogeneity test and exogeneity test with SEM.Because we have learn these techniques in chapter 17, so we will jump to the chapter 20.\n:::\n\n\n## Endogeneity test\n\n<!-- insert image here -->\n\n##\n\n### Concepts and definitions\n\nSimultaneity testing is essentially testing whether a (endogenous) regressor is related to the error term ( $u_t$ ).\n\n- if relevant, there is a problem of simultaneity, so we need to find other estimation method different from OLS;\n\n- if not, It will seems that there is no problem of simultaneity and you can use the OLS method as usual.\n\n**Test of Simultaneity** also known as **Hausman test of endogeneity**.\n\n- **Hausman specification error test ** can be used to test simultaneous problems.\n\n\n::: {.notes}\n联立性检验在本质上是检验一个（内生）回归元是否与误差项（$u_t$）相关。- 如果相关，就存在联立性问题，从而需要找到不同于OLS的估计方法；- 如果不相关，则认为不存在联立性问题，可以继续使用OLS方法**豪斯曼设定误差检验** (Hausman specification error test)的**一种形式**可用于检验联立性问题。**豪斯曼联立性检验**又被称为**豪斯曼内生性检验** (Hausman test of endogeneity)\n:::\n\n\n##\n\n### The theory principle\n\n\nGiven the structural SEM:\n\n$$\n\\begin{align}\nQ &= \\alpha_0+\\alpha_1P_t+\\alpha_2I_t+\\alpha_3R_t+u_{t1}   &(\\alpha_1<0,\\alpha_2>0)  &&\\text{(demand function)}\\\\\nQ &= \\beta_0+\\beta_1P_t+u_{t2}  &(\\beta_1>0) &&\\text{(supply function)}\n\\end{align}\n$$\n\nwhere: P=price; I=income; R=wealth\n\nIt is easy to get the reduced SEM:\n\n$$\n\\begin{align}\nP_t &= \\pi_{11}+ \\pi_{21}I_t + \\pi_{31} R_t + v_{t1} &&\\text{(eq1)}\\\\\nQ_t &= \\pi_{12}+ \\pi_{22}I_t + \\pi_{33} R_t + v_{t2} &&\\text{(eq2)}\n\\end{align}\n$$\n\n\n##\n\n### The theory principle (1/2)\n\nWe can directly estimate reduced equation 1 (price equation) by OLS method:\n\n$$\n\\begin{align}\nP_t &= \\hat{\\pi}_{11}+ \\hat{\\pi}_{21}I_t + \\hat{\\pi}_{31} R_t + \\hat{v}_{t1} &&\\text{(OLS Estimation)} \\\\\n&= \\hat{P_t} +\\hat{v}_{t1}\n\\end{align}\n$$\n\nThen, we can use the OLS estimation results to construct two **test equations**:\n\n$$\n\\begin{align}\nQ_t &= \\beta_0+\\beta_1\\hat{P_t} + \\beta_1 \\hat{v}_{t1} +u_{t2} & && \\text{(Hausman test equation)}\\\\\nQ_t &= \\beta_0+\\beta_1 {P_t} + \\beta_1\\hat{v}_{t1} +u_{t2} & &&\\text{(Pindyck test equation)} \\\\\n\\end{align}\n$$\n\n>Hausman test:\n\n>- Null hypothesis  $H_0$  : No simultaneity problems, so that  $\\hat{v}_{t1}$  is uncorrelated with  $u_{t2}$ ;\n\n>- Alternative hypothesis  $H_1$  : exist simultaneity problems, so that  $\\hat{v}_{t1}$  is correlated with  $u_{t2}$ ;\n\n\n\n##\n\n### The theory principle (2/2)\n\nWe can directly estimate reduced equation 1 (price equation) by OLS method:\n\n$$\n\\begin{align}\nP_t &= \\hat{\\pi}_{11}+ \\hat{\\pi}_{21}I_t + \\hat{\\pi}_{31} R_t + \\hat{v}_{t1} &&\\text{(OLS Estimation)} \\\\\n&= \\hat{P_t} +\\hat{v}_{t1}\n\\end{align}\n$$\n\nThen, we can use the OLS estimation results to construct two **test equations**:\n\n$$\n\\begin{align}\nQ_t &= \\beta_0+\\beta_1\\hat{P_t} + \\beta_1 \\hat{v}_{t1} +u_{t2} & && \\text{(Hausman test equation)}\\\\\nQ_t &= \\beta_0+\\beta_1 {P_t} + \\beta_1\\hat{v}_{t1} +u_{t2} & &&\\text{(Pindyck test equation)} \\\\\n\\end{align}\n$$\n\n\nThus, we only need to test  $\\beta_1$  in the Hausman test.\n\n- if the test  is **not significant**,  $H_0$  can not be rejected, and conclude [No exist]{.red} of simultaneity problems.\n\n- if the test  is **significant**,  $H_0$  should be rejected, and conclude the [exist]{.red} of simultaneity problems.\n\n\n\n\n##\n\n### Hausman test steps\n\nThe steps of Hausman test include:\n\n- step 1: conduct the fist OSL estimation  $P_t = \\hat{\\pi}_{11}+ \\hat{\\pi}_{21}I_t + \\hat{\\pi}_{31} R_t + \\hat{v}_{t1}$ , and obtain its residuals  $\\hat{v_t}$ \n\n- step 2：conduct the second OSL estimation  $Q_t = \\beta_0+\\beta_1 \\hat{P_t} + \\beta_1\\hat{v}_{t1} +u_{t2}$ , and apply t test for  $\\hat{v}_{1t}$ ,then judge according former rules.\n\n::: {.callout-tip title=\"Pindyck and Rubinfeld' suggestion\" .font-115}\n\nTo esitimat more efficiently, Pindyck and Rubinfeld suggest the second OSL estimation shoild be:  \n\n$$\nQ_t = \\beta_0+\\beta_1 P_t + \\beta_1\\hat{v}_{t1} +u_{t2}\n$$ \n\n:::\n\n\n## Example\n\n<!-- insert image here -->\n\n##\n\n###  Structural and reduced SEM\n\nIn the truffle case, given Structural SEM：\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_i &= \\alpha_0+\\alpha_1P_i+\\alpha_2PS_i+\\alpha_3DI_i+u_{i1}  &&\\text{(demand function)}\\\\\nQ_i &= \\beta_0+\\beta_1P_i+\\beta_2PF_i+u_{i2}    &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\nAnd obtain its reduced SEM：\n\n$$\n\\begin{cases}\n\\begin{align}\nP_i &= \\pi_{11}+ \\pi_{21}PS_i+\\pi_{31}DI_i+\\pi_{41}PF_i+v_{i1} \\\\\nQ_i &= \\pi_{12}+\\pi_{22}PS_t+\\pi_{32}DI_t+\\pi_{42}PF_i+v_{i2}\n\\end{align}\n\\end{cases}\n$$\n\n\n##\n\n### Structural and reduced coefficients\n\nThe relationship between **reduced coefficients** and **structural coefficients** is:\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n$$\n\\begin{cases}\n\\begin{align}\n& \\pi_{11} = \\frac{\\beta_0-\\alpha_0}{\\alpha_1-\\beta_1}\\\\\n& \\pi_{21} = - \\frac{\\alpha_2}{\\alpha_1-\\beta_1}\\\\\n& \\pi_{31} = - \\frac{\\alpha_3}{\\alpha_1-\\beta_1}\\\\\n& \\pi_{41} = \\frac{\\beta_2}{\\alpha_1-\\beta_1}\\\\\n& v_{i1} = \\frac{u_{i2}-u_{i1}}{\\alpha_1-\\beta_1}\n\\end{align}\n\\end{cases}\n$$\n\n:::\n\n\n::: {.column width=\"40%\"}\n\n\n$$\n\\begin{cases}\n\\begin{align}\n& \\pi_{12} = - \\frac{\\alpha_1\\beta_0-\\alpha_0\\beta_1}{\\alpha_1-\\beta_1}  \\\\\n& \\pi_{22} = - \\frac{\\alpha_2\\beta_1}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{32} = - \\frac{\\alpha_3\\beta_1}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{42} =   \\frac{\\alpha_1\\beta_2}{\\alpha_1-\\beta_1} \\\\\n& v_{i2} = \\frac{\\alpha_1u_{i2}-\\beta_1u_{i1}}{\\alpha_1-\\beta_1}\n\\end{align}\n\\end{cases}\n$$\n\n:::\n\n::::\n\n\n##\n\n### First OLS estimation on price equation\n\nAccording to the first step, OLS method is used to estimate the **reduced price equation** and obtain  $\\hat{P_i},\\hat{v}_{i1}$ \n\n>  The **reduced price equation** :\n\n$$\n\\begin{align}\nP_i & = \\hat{\\pi}_{11}+ \\hat{\\pi}_{21} PS_i + \\hat{\\pi}_{31} DI_i + \\hat{\\pi}_{41} PF_i + \\hat{v}_{i1} \\\\\n& = \\hat{P_i} + \\hat{v}_{i1}\n\\end{align}\n$$\n\n\n##\n\n### First OLS estimation on price equation\n\n\n\nThe raw R report for the OLS estimation of **reduced price equation** :\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Hausman_models$mod.P, data = truffles)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-20.4825  -3.5927   0.2801   4.5326  12.9210 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -32.5124     7.9842  -4.072 0.000387 ***\nPS            1.7081     0.3509   4.868 4.76e-05 ***\nDI            7.6025     1.7243   4.409 0.000160 ***\nPF            1.3539     0.2985   4.536 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.597 on 26 degrees of freedom\nMultiple R-squared:  0.8887,\tAdjusted R-squared:  0.8758 \nF-statistic: 69.19 on 3 and 26 DF,  p-value: 1.597e-12\n```\n\n\n:::\n:::\n\n\n\n##\n\n### First OLS estimation on price equation (1/2)\n\nThe tidy R report for the OLS estimation of **reduced price equation** :\n\n$$\n\\begin{alignedat}{999}\n&\\widehat{P}=&&-32.51&&+1.71PS&&+7.60DI&&+1.35PF\\\\\n&\\text{(t)}&&(-4.0721)&&(4.8682)&&(4.4089)&&(4.5356)\\\\\n&\\text{(se)}&&(7.9842)&&(0.3509)&&(1.7243)&&(0.2985)\\\\\n&\\text{(fitness)}&& n=30;&& R^2=0.8887;&& \\bar{R^2}=0.8758\\\\\n& && F^{\\ast}=69.19;&& p=0.0000\\\\\n\\end{alignedat}\n$$\n\n::: {.callout-note title=\"Questions\" .font-115}\n\nPlease explain the regression results ?\n\n:::\n\n\n##\n\n### First OLS estimation on price equation (2/2)\n\nAfter OLS estimating of the **reduced price equation**, we can obtain  $\\hat{P_i},\\hat{v}_{i1}$ :\n\n<br>\n\n\n\n::: {#tbl-data-Hausman-step1 .cell layout-align=\"center\" tbl-cap='Estimate the price equation and get hat.Pi and hat.v1i'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-d1a618d189cf895b1419\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d1a618d189cf895b1419\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\"],[29.64,40.23,34.71,41.43,53.37,38.52,54.33,40.56,67.34999999999999,49.65,58.17,66.87,49.95,64.95,52.68,61.2,80.55,89.94,70.77,57.33,46.23,77.43000000000001,83.01000000000001,70.70999999999999,66.75,76.8,83.7,81,88.44,105.45],[19.89,13.04,19.61,17.13,22.55,6.37,15.02,10.22,23.64,16.12,24.55,18.92,11.94,18.93,12.6,20.49,22.94,21.08,16.68,17.61,16.62,20.99,24.53,19.67,23.29,16.64,20.81,14.95,26.27,20.65],[19.97,18.04,22.36,20.87,19.79,15.98,17.94,17.09,22.72,15.74,24.64,23.7,15.93,23.34,15.21,26.04,22.95,27.1,23.65,20.06,26.38,24.28,26.64,22.65,19.68,23.82,28.98,18.52,28.16,28.43],[2.103,2.043,1.87,1.525,2.709,2.489,2.294,2.196,3.885,3.169,2.623,3.007,3.367,3.29,3.746,3.518,4.381,4.121,3.82,4.398,3.764,4.524,4.815,3.67,4.392,4.603,4.632,4.894,5.125,4.836],[10.52,19.67,13.74,17.95,13.71,24.95,24.17,23.61,19.52,20.03,15.38,22.98,25.76,25.17,25.82,19.31,26.02,29.65,27.45,18,18.87,24.58,25.25,24.24,22.63,27.35,27.8,30.34,24.12,34.01],[31.8304,40.4658,38.5011,39.033,40.449,47.4863,48.2958,45.3406,62.2606,45.5848,50.3407,61.9441,55.1726,66.4457,56.9053,64.85720000000001,75.2247,85.25149999999999,74.0915,59.5591,66.71250000000001,76.6341,83.7847,66.8969,65.13290000000001,80.1992,89.843,77.4066,87.208,98.8622],[-2.1904,-0.2358,-3.7911,2.397,12.921,-8.9663,6.0342,-4.7806,5.0894,4.0652,7.8293,4.9259,-5.2226,-1.4957,-4.2253,-3.6572,5.3253,4.6885,-3.3215,-2.2291,-20.4825,0.7959000000000001,-0.7747000000000001,3.8131,1.6171,-3.3992,-6.143,3.5934,1.232,6.5878]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>P<\\/th>\\n      <th>Q<\\/th>\\n      <th>PS<\\/th>\\n      <th>DI<\\/th>\\n      <th>PF<\\/th>\\n      <th>hat.Pi<\\/th>\\n      <th>hat.vi<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"tip\",\"pageLength\":6,\"rownames\":false,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"P\",\"targets\":1},{\"name\":\"Q\",\"targets\":2},{\"name\":\"PS\",\"targets\":3},{\"name\":\"DI\",\"targets\":4},{\"name\":\"PF\",\"targets\":5},{\"name\":\"hat.Pi\",\"targets\":6},{\"name\":\"hat.vi\",\"targets\":7}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[6,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n##\n\n### Second OLS estimation on Hausman equation (1/3)\n\nWe proceed to the second step of the endogeneity test:\n\n$$\n\\begin{align}\nQ_t &= \\beta_0+\\beta_1\\hat{P_t} + \\beta_1 \\hat{v}_{t1} +u_{t2} & && \\text{(Hausman  equation)}\\\\\nQ_t &= \\beta_0+\\beta_1 {P_t} + \\beta_1\\hat{v}_{t1} +u_{t2} & &&\\text{(Pindyck equation)} \\\\\n\\end{align}\n$$\n\n<br>\n\n::: {.callout-note title=\"Hausman and Pindyck test models\" .font-115}\n\nYou can use any of these two test models:\n\n1. Hausman equation for Hausman test\n\n2. Pindyck equation for Pindyck test\n\nSO, Let us do the Hausman test firstly, and then the Pindyck test.\n\n:::\n\n##\n\n### Second OLS estimation on Hausman equation (2/3)\n\nThe raw R report for the **Hausman test equation** show as following:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Hausman_models$mod.Q.Hausman, data = truffles_Hausman)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-7.4756 -2.8917  0.2775  3.3937  5.3796 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 11.94585    2.60369   4.588 9.21e-05 ***\nhat.Pi       0.10383    0.04001   2.595  0.01510 *  \nhat.vi       0.33801    0.11304   2.990  0.00589 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.803 on 27 degrees of freedom\nMultiple R-squared:  0.3673,\tAdjusted R-squared:  0.3205 \nF-statistic: 7.838 on 2 and 27 DF,  p-value: 0.00207\n```\n\n\n:::\n:::\n\n\n\n\n##\n\n### Second OLS estimation on Hausman equation (3/3)\n\nThe tidy R report for the **Hausman test equation** show as following:\n\n\n$$\n\\begin{alignedat}{999}\n&\\widehat{Q}=&&+11.95&&+0.10\\hat{P}&&+0.34\\hat{v}_{1}\\\\\n&\\text{(t)}&&(4.5880)&&(2.5952)&&(2.9901)\\\\\n&\\text{(se)}&&(2.6037)&&(0.0400)&&(0.1130)\\\\\n&\\text{(fitness)}&& n=30;&& R^2=0.3673;&& \\bar{R^2}=0.3205\\\\\n& && F^{\\ast}=7.84;&& p=0.0021\\\\\n\\end{alignedat}\n$$\n\nConclusions of Hausman simultaneity test:\n\n- The coefficient of  $\\hat{v}_{1i}$  is 0.34，  $t^{\\ast}=2.9901>t{(\\alpha/2,n-3)}=$  2.4726599。(given  $\\alpha=0.01$ \n)\n\n- Hence, the t test on coefficient of  $\\hat{v}_{i1}$  is **significantly** (given  $\\alpha=0.01$ ). Thus we should **reject**  $H_0$ , and accept  $H_1$ . Finally conclude that there is **no exist** of simultaneity problem。\n\n\n##\n\n### Second OLS estimation on Pindyck equation (1/2)\n\nThe raw R report for the **Pindyck test equation** show as following:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Hausman_models$mod.Q.Pindyck, data = truffles_Hausman)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-7.4756 -2.8917  0.2775  3.3937  5.3796 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 11.94585    2.60369   4.588 9.21e-05 ***\nP            0.10383    0.04001   2.595   0.0151 *  \nhat.vi       0.23418    0.11991   1.953   0.0613 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.803 on 27 degrees of freedom\nMultiple R-squared:  0.3673,\tAdjusted R-squared:  0.3205 \nF-statistic: 7.838 on 2 and 27 DF,  p-value: 0.00207\n```\n\n\n:::\n:::\n\n\n\n\n\n##\n\n### Second OLS estimation on Pindyck equation (2/2)\n\nThe tidy R report for the **Pindyck test equation** show as following:\n\n<!---\nfun_report_eq(Hausman_models$mod.Q.Pindyck,lm.dt =truffles_Hausman)\n--->\n\n$$\n\\begin{alignedat}{999}\n&\\widehat{Q}=&&+11.95&&+0.10P&&+0.23\\hat{v}_{1}\\\\\n&\\text{(t)}&&(4.5880)&&(2.5952)&&(1.9529)\\\\\n&\\text{(se)}&&(2.6037)&&(0.0400)&&(0.1199)\\\\\n&\\text{(fitness)}&& n=30;&& R^2=0.3673;&& \\bar{R^2}=0.3205\\\\\n& && F^{\\ast}=7.84;&& p=0.0021\\\\\n\\end{alignedat}\n$$\n\nConclusions of Pindyck simultaneity test:\n\n- The coefficient of  $\\hat{v}_{i1}$  is 0.23, and  $t^{\\ast}=1.9529>t{(\\alpha/2,n-3)}=$  1.7032884. (given  $\\alpha=0.1$ )\n\n- Hence, the t test on coefficient of  $\\hat{v}_{i1}$  is **significantly** (given  $\\alpha=0.01$ ). Thus we should **reject**  $H_0$ , and accept  $H_1$ . Finally conclude that there is **no exist** of simultaneity problem。\n\n\n# 19.4 Exogeneity test $^{\\ast}$ {#test-exogeneity .monash-bg-blue .mcenter}\n\n::: {.notes}\n\nBecause we have learn these techniques in chapter 17, so we will jump to the chapter 20.\n\n:::\n\n\n\n## Exogeneity test\n\n<!-- insert image here -->\n\n##\n\n### Exogeneity test\n\nellipsis ...\n\n# 19.5 class summary {#class-summary .monash-bg-blue .mcenter}\n\n\n##\n\n### Key points and conclusions (1/3)\n\n1. The problem of identiﬁcation precedes the problem of estimation.\n\n2. The identiﬁcation problem asks whether one can obtain unique numerical estimates of the structural coefﬁcients from the estimated reduced-form coefﬁcients.\n\n3. If this can be done, an equation in a system of simultaneous equations is identiﬁed. If this cannot be done, that equation is un- or under-identiﬁed.\n\n4. An identiﬁed equation can be just identiﬁed or overidentiﬁed. In the former case, unique values of structural coefﬁcients can be obtained; in the latter, there may be more than one value for one or more structural parameters.\n\n::: {.notes}\n1. 识别问题的考虑应先于估计问题。\n\n2. 识别问题是问我们能否从约简系数估计值求出结构系的唯一数值估计值。\n\n3. 如果能做到，就说联立方程组中的某个方程是可识别的；如果做不到，该方程就是不可识别或识別不足的。\n\n4. 一个可识别的方程可以是恰好识别的或过度识别的。在前一种情形中，可以得到的唯一值；而在后一种情形中，可以得到不止一个估计值。\n\n:::\n\n##\n\n### Key points and conclusions (2/3)\n\n5. The identiﬁcation problem arises because the same set of data may be compatible with different sets of structural coefﬁcients, that is, different models. Thus, in the regression of price on quantity only, it is difﬁcult to tell whether one is estimating the supply function or the demand function, because price and quantity enter both equations.\n\n6. To assess the identiﬁability of a structural SEM, one may apply the technique of reduced-form SEM.\n\n7. Although the order condition is easy to apply, it provides only a necessary condition for identiﬁcation. On the other hand, the rank\ncondition is both a necessary and sufﬁcient condition for identiﬁcation.\n\n::: {.notes}\n\n5. 识別问题之所以出现，是因为同样的数据集适合于不同的的模型.\n\n6. 要判断一个结构方程的可识别性，我们可以应用约简型方程的技术，把一个内生变量表达为前定变量的函数。\n\n7. 这种耗时的程序由于**阶条件**或**秩条件**的利用而得以避免。阶条件虽然易用应用，但它仅是可识别性的**必要而非充分**条件；秩条件则是可识别性的**充分必要**条件。\n\n:::\n\n##\n\n### Key points and conclusions (2/3)\n\n8. In the presence of **simultaneity**, OLS is generally not applicable But if one wants to use it nonetheless, it is imperative to test for simul-taneity explicitly. The Hausman speciﬁcation test can be used for this purpose.\n\n9. Although in practice deciding whether a variable is endogenous or exogenous is a matter of **judgment**, one can use the Hausman speciﬁcation test to determine whether a variable or group of variables is endogenous or exogenous.\n\n10. Although they are in the same family, the concepts of **causality** and **exogeneity** are different and one may not necessarily imply the other. In practice it is better to keep those concepts separate.\n\n::: {.notes}\n\n8. 当出现联立性问题时，OLS一般而言是不适用的。但如果我们仍想用它，则必须明确地进行联立性检验，为此，可利用豪斯曼内生性检验方法。\n\n9. 虽然在实践中一个变量是内生或外生的，是凭判断而决定的，但我们可以用豪斯曼设定检验判定一个或一组变量是内生的还是外生的。\n\n10. 因果关系和外生性虽属于同一类问题，但它们的概念却是不同的。其中一个概念并不蕴含另一个概念。在实践中，仍然是把这两个概念区分开来为好。\n:::\n\n\n## End Of This Chapter{.center-h background-color=\"aliceblue\"  background-image=\"pic/thank-you-gif-funny-little-yellow.gif\" background-size=\"600px\"  background-position=\"center\" background-opacity=\"0.8\" style=\"font-size:75px !important\"}\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}