{
  "hash": "3b2d1e06532f76575361c4f3589d1eea",
  "result": {
    "engine": "knitr",
    "markdown": "---\npagetitle: \"Advanced Econometrics III\"\nunitcode: \"(Econometrics III)\"\nunitname: \"Advanced Econometrics III\"\nauthor: \"Hu Huaping (胡华平)\"\nemail: \"huhuaping01 at hotmail.com\"\nuniversity: \"NWAFU (西北农林科技大学)\"\ndepartment: \"School of Economics and Management (经济管理学院)\"\nsubtitle: \"Chapter 20. How to Estimate SEM ?\"\ndate: \"2024-09-25\"\n#keep-md: true\nformat: \n  revealjs: \n    footer: \"Chapter 20. How to Estimate SEM ?\"\n---\n\n\n\n\n## 环境准备{visibility=\"hidden\"}\n\n\n\n\n\n\n\n\n\n\n\n# 标题页 {visibility=\"hidden\"}\n\n## <br>Advanced Econometrics III{background-image=\"pic/slide-front-page.jpg\" #etc5523-title .center-h style=\"font-size:65px\" visibility=\"uncounted\"}\n\n### **(Econometrics III)**{.monash-black .center-h style=\"font-family:'sans-serif'; font-size:65px !important\"}\n\n\n### Chapter 20. How to Estimate SEM ?{.monash-blue .center-h style=\"font-size:70px !important\"}\n\n<br>\n\n#### Hu Huaping (胡华平) {.center-h .monash-black}\n\n#### huhuaping01 at hotmail.com {.center-h .monash-black style=\"font-family:'sans-serif';\"}\n\n#### School of Economics and Management (经济管理学院) {.center-h .monash-black}\n\n\n#### 2024-09-25 {.center-h .monash-black}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n\n# Part 2：Simultaneous Equation Models (SEM){.monash-bg-blue .mcenter visibility=\"uncounted\"}\n\n::: {.font-110}\n\nChapter 17. Endogeneity and Instrumental Variables\n\nChapter 18. Why Should We Concern SEM ?\n\nChapter 19. What is the Identification Problem ?\n\n[Chapter 20. How to Estimate SEM ?]{.red}\n\n:::\n\n\n# Chapter 20. How to Estimate SEM?{#chpt20 .monash-bg-blue .mcenter}\n\n::: {.font-110}\n\n[20.1 Approaches to Estimation](#approaches)\n\n[20.2 General least squares (OLS)](#LS)\n\n[20.3 Indirect least squares (ILS)](#ILS)\n\n[20.4 Two-stage least square method (2SLS)](#TSLS)\n\n[20.5 Truffle case](#truffle)\n\n[20.6 Cod case](#cod)\n\n[20.7 Exercise and computation](#exercise)\n\n:::\n\n\n# 20.1 Approaches to Estimation{#approaches .monash-bg-blue .mcenter}\n\n\n## Estimation Approaches\n\n<!-- insert image here -->\n\n##\n\n### Approaches options\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\nIn order to estimate the structural SEM, two approaches can be adopted:\n\n- **Single equation method**, also known as **limited information methods**.\n\n> estimate each equation in SEM one by one, considering only the constraints in that equation\n\n- **System method** , also known as **full information method**\n\n>estimate all the equations in the model simultaneously, taking into account all the constraints in the SEM\n\n::: {.notes}\n为了估计结构方程，可采取两种方法：- 单方程法，又称有限息法(limited information methods) 。- 我们逐个估计(联立)方程组中的每一个方程，仅考虑对该方程的约束(如对某些变量的排除)而不考虑对其他方程的约束- 方程组法(或系统法)，又称完全信息法 (full information methods)- 我们同时估计模型中的全部方程，适当考虑了因某些变量被排除而对方程组造成的全部约束\n:::\n\n##\n\n### Instrumental variables\n\nInstrumental variables are often used to estimate simultaneous equation problems, mainly including three IV techniques for **System method** :\n\n- **Three-stage least squares** (**3SLS**)：Applicable in a few cases\n\n- **Generalized  moment method**( **GMM**)：It is commonly used for dynamic model problems\n\n- **Full information maximum likelihood**( **FIML**)：It has much theoretical value and it brings no advantage over 3SLS, but is much more complicated to compute.\n\n::: {.notes}\n工具变量往往被用于估计联立方程问题，主要又包括三类方法：\n:::\n\n\n##\n\n### single or simultaneously method\n\nConsider the following SEM:\n\n$$\n\\begin{cases}\n\\begin{alignedat}{9}\n&  Y_{t1} &-\\gamma_{21}Y_{t2}&-\\gamma_{31}Y_{t3} & &-\\beta_{01}&-\\beta_{11}X_{t1} &  & &= &u_{t1} \\\\\n& & Y_{t2} &-\\gamma_{32} Y_{3t} & & -\\beta_{02}&-\\beta_{12}X_{1t} &- \\beta_{22}X_{2t} & &= &u_{t2}\\\\\n&-\\gamma_{13}Y_{t1} &  &+ Y_{t3} & & -\\beta_{03}&-\\beta_{13}X_{1t} &-\\beta_{23}X_{2t} & &= &u_{t3} \\\\\n&-\\gamma_{14}Y_{t1}&-\\gamma_{24}Y_{t2} &  &+Y_{t4}   &-\\beta_{04} & & &-\\beta_{34}X_{t3} &= &u_{t4}\n\\end{alignedat}\n\\end{cases}\n$$\n\n- If you focus only on estimating the third equation, we can use the **single equation method** , which the variables  $Y_2, Y_4, X_3$  were excluded from the estimation.\n\n- If you want to estimate all four equations **simultaneously**, you should use the **system method**, and it will take into account all the constraints on multiple equations in the system.\n\n::: {.notes}\n- 如果仅仅关注于估计第三个方程，采用**单方程法**将只考虑此方程，也即仅注意变量  $Y_2,Y_4,X_3$ 被排除在此方程之外。- 如果希望**同时**估计全部四个方程，采用**方程组法**将会对方程组中多个方程的全部约束都考虑进来。\n:::\n\n##\n\n### simultaneously method\n\nIn order to use all information  of SEM, it is most desirable to apply **system method**, such as **full information maximum likelihood** (FIML).\n\nIn practice, however, **systems method** are not commonly used for the following main reasons:\n\n1. The computational burden is too great.\n\n2. Systematic methods such as FIML often bring highly nonlinearity on parameters  , which are difficult to determine and caculate.\n\n3. If there is one or more **specification error** in SEM (eg. an incorrect functional form or missing variables), the error will be passed to the remaining equations. As a result, the system method becomes very sensitive to the specification errors.\n\n::: {.notes}\n为了保持联立方程模型的品质，最理想的应是使用**方程组法**，比如**完全信息极大似然法** (full information maximum likelihood, FIML) 。然而，实际上**方程组法**并不常用，主要原因包括：1. 计算上的负担太大。2. 像FIML这样的系统方法常常导致参数的高度非线性解，以致难以确定。3. 如果方程组中的一个或多个方程有**设定误差**(比如说，一个错误的函数形式或漏掉有关变量)，则误差将传递至其余方程。其结果是，方程组法变得对设定误差非常敏感。\n:::\n\n\n# 20.2 Least squares  approach (LS){#LS .monash-bg-blue .mcenter}\n\n\n## OLS Approarch for recursive model\n\n<!-- insert image here -->\n\n\n##\n\n### Recursive model\n\n**Recursive model** : also known as the **triangle model**  or **causality  model**.\n\n>The simultaneous disturbance terms in different equations are unrelated, and each equation exhibits a one-way causal dependence.\n\nConsider the following structural SEM:\n\n$$\n\\begin{cases}\n\\begin{alignat}{6}\nY_{t1} =  & & & & +\\beta_{01}& + \\beta_{11}X_{t1} & + \\beta_{21}X_{t2}  & & +u_{t1} \\\\\nY_{t2} =  & + \\gamma_{12}Y_{1t} & & &+\\beta_{02} & + \\beta_{12}X_{t1} & + \\beta_{22}X_{t2} & & + u_{t2}\\\\\nY_{t3} =  & + \\gamma_{13}Y_{t1}& + \\gamma_{23}Y_{t2}& &+\\beta_{03} & + \\beta_{13}X_{t1} & + \\beta_{23}X_{t2} & & + u_{t3} \\\\\n\\end{alignat}\n\\end{cases}\n$$\n\n::: {.notes}\n递归模型(recursive model)：也称为三角形模型(triangular model)或因果性(causalmodel)模型。不同方程中的同期干扰项是不相关的，每个方程都展现一种单向的因果依赖关系。考虑下面的联立方程模型：\n:::\n\n##\n\n### Zero contemporaneous correlation\n\n$$\n\\begin{cases}\n\\begin{alignat}{6}\nY_{t1} =  & & & & +\\beta_{01}& + \\beta_{11}X_{t1} & + \\beta_{21}X_{t2}  & & +u_{t1} \\\\\nY_{t2} =  & + \\gamma_{12}Y_{1t} & & &+\\beta_{02} & + \\beta_{12}X_{t1} & + \\beta_{22}X_{t2} & & + u_{t2}\\\\\nY_{t3} =  & + \\gamma_{13}Y_{t1}& + \\gamma_{23}Y_{t2}& &+\\beta_{03} & + \\beta_{13}X_{t1} & + \\beta_{23}X_{t2} & & + u_{t3} \\\\\n\\end{alignat}\n\\end{cases}\n$$\n\nIt is easy to find that the contemporaneous disturbance terms in different equations are irrelevant (namely **zero contemporaneous correlation**) :\n\n\n$$\ncov(u_{t1},u_{t2})=cov(u_{t1},u_{t3})=cov(u_{t2},u_{t3})=0\n$$\n\n- Since the first equation' right-hand side only contains exogenous variables, and are not correlated with disturbance terms, so this equation satisfies the CLRM and OLS can be applied directly to  it.\n\n\n-  because  $cov(u_{t1},u_{t2})=0$ , and  $cov(Y_{t1},u_{t2})=0$ . Thus OLS can be applied directly to  it.\n\n- because  $cov(u_{t1},u_{t3})=0$ , and  $cov(Y_{t1},u_{t3})=0$ . Also  $cov(u_{t1},u_{t3})=0$ , and  $cov(Y_{t2},u_{t3})=0$ . Thus OLS can be applied directly to  it.\n\n::: {.notes}\nzero contemporaneous correlation我们很容易发现,不同方程中的同期干扰项是不相关的(或者说是零同期相关)：对于第一个方程。因为它的右边仅含有外生变量，假定外生变量与干扰项均不相关，所以此方程满足经典OLS解释变量与干扰项不相关的基本假定。因而OLS可直接应用于此方程的估计。\n:::\n\n\n##\n\n### Visualize graphically\n\nWe can also visualize it graphically:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![SEM in recursive form](pic/chpt20-recursive-graph.png){fig-align='center' width=948}\n:::\n:::\n\n\n\n\n\n<!-- ![](pic/chpt20-recursive-graph.png) {#fig-recursive-graph fig-cap=\"SEM in recursive form\" .center width=\"60%\"} -->\n\n##\n\n### wage-price model\n\nLet's look at the **wage-price model**:\n\n\n$$\n\\begin{cases}\n\\begin{align}\nP_t &= \\beta_0+\\beta_1UN_t+\\beta_2R_t+\\beta_3M_t+u_{t2}  &&\\text{(price equation)}\\\\\nW_t &= \\alpha_0+\\alpha_1UN_t+\\alpha_2P_t+u_{t1}   &&\\text{(wage equation)}\n\\end{align}\n\\end{cases}\n$$\n\nWhere:\n\n- W, the money wage rate;\n- UN, unemployment, %;\n- P, price rate;\n- R, the cost of capital rate;\n- M, import price change rate of raw materials.\n\n::: {.notes}\n- 价格方程假定当前价格变化率是资本和原料价格变化率、劳动生产率变化率以及前期工资变化率等的函数。- 工资方程则表示当前工资变化率取决于当前价格变化率和失业率。- 货币工资变化率W- 失业率UN，%- 价格变化率P- 资本成本变化率R- 进口原材料的价格变化率M\n:::\n\n\n# 20.3 Indirect least squares (ILS){#ILS .monash-bg-blue .mcenter}\n\n## ILS approach with Just Identification model\n\n<!-- insert image here -->\n\n##\n\n### indirect least squares estimates\n\nFor a just or exactly identiﬁed structural equation, the method of obtaining the estimates of the structural coefﬁcients from the OLS estimates of the reduced-form coefﬁcients is known as the method of **Indirect Least Squares** (ILS), and the estimates thus obtained are known as the **indirect least squares estimates**.\n\n**ILS** involves the following three steps:\n\n- Step 1. We ﬁrst obtain the reduced-form SEM.\n\n- Step 2. We apply **OLS** to the reduced-form SEM individually.\n\n- Step 3. We obtain estimates of the original structural coefﬁcients from the estimated reduced-form coefﬁcients obtained in Step 2.\n> If an equation is **exactly identiﬁed**, there is one-to-one mapping between the structural and reduced coefficients.\n\n::: {.notes}\n> This operation is permissible since the explanatory variables in these equations are predetermined and hence uncorrelated with the stochastic disturbances. The estimates thus obtained are consistent.对一个恰好识别的结构方程，从**约简型系数**的OLS估计值获得**结构系数**估计值的方法叫做间接最小二乘法 (method of indirect least squares, ILS)，而如此得到的估计值称**间接最小二乘估计值**。间接最小二乘法(ILS方法)包含以下三个步骤:- step 1：先求约简型方程。从结构方程组解出约简型方程，使得在每个方程的因变量都成为唯一的内生变量，并且仅仅是前定变量(外生或滞后内生)和随机误差项的函数。- step 2：对约简型方程逐个应用OLS。因为这些方程中的解释变量是前定的并因而与随机干扰项不相关，所以这种做法是合适的，由此得到的估计值是一致的。- step 3: 从得到的约简型系数的估计值求原始结构系数的估计值 。若方程恰可识别，则结构与约简型系数之间有一一对应关系，就是说可以从后者导出前者的唯一估计值。\n:::\n\n\n## Case demo: US crop supply and demand\n\n<!-- insert image here -->\n\n##\n\n### variables\n\nThe variables in the US crop supply and demand case are illustrated below\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-94aff349b592a3cb40a6\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-94aff349b592a3cb40a6\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>variables in the model<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\"],[\"Q\",\"P\",\"X\"],[\"Crop yield index\",\"Agricultural products purchasing prices index\",\"Capital personal consumption expenditure\"],[\"(1996=100)\",\"(1990-1992=100)\",\"(In 2007 dollars)\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>vars<\\/th>\\n      <th>label<\\/th>\\n      <th>note<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":3,\"rownames\":false,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"vars\",\"targets\":1},{\"name\":\"label\",\"targets\":2},{\"name\":\"note\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[3,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n##\n\n### Data set\n\nThe data for US crop supply and demand case show here:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-cafd247841746ab47be1\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-cafd247841746ab47be1\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>sample data (n=30)<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\"],[\"1975 \",\"1976 \",\"1977 \",\"1978 \",\"1979 \",\"1980 \",\"1981 \",\"1982 \",\"1983 \",\"1984 \",\"1985 \",\"1986 \",\"1987 \",\"1988 \",\"1989 \",\"1990 \",\"1991 \",\"1992 \",\"1993 \",\"1994 \",\"1995 \",\"1996 \",\"1997 \",\"1998 \",\"1999  \",\"2000 \",\"2001 \",\"2002\",\"2003\",\"2004 \"],[66,67,71,73,78,75,81,82,71,81,85,82,84,80,86,90,90,96,91,101,96,100,104,105,108,108,108,107,108,112],[88,87,83,89,98,107,111,98,108,111,98,87,86,104,109,103,101,101,102,105,112,127,115,107,97,96,99,105,111,117],[4789,5282,5804,6417,7073,7716,8439,8945,9775,10589,11406,12048,12766,13685,14546,15349,15722,16485,17204,18004,18665,19490,20323,21291,22491,23862,24722,25501,26463,27937]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>year<\\/th>\\n      <th>Q<\\/th>\\n      <th>P<\\/th>\\n      <th>X<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"tip\",\"pageLength\":7,\"rownames\":false,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"year\",\"targets\":1},{\"name\":\"Q\",\"targets\":2},{\"name\":\"P\",\"targets\":3},{\"name\":\"X\",\"targets\":4}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[7,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n##\n\n### Structural SEM\n\nSo we can construct the following structural SEM:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ &= \\alpha_0+\\alpha_1P_t+\\alpha_2X_t+u_{t1}   &(\\alpha_1<0,\\alpha_2>0)  &&\\text{(demand function)}\\\\\nQ &= \\beta_0+\\beta_1P_t+u_{t2}  &(\\beta_1>0) &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\n>where：\n- $Q=$Crop yield index;\n- $P=$Agricultural products purchasing prices index;\n- $X=$Capital personal consumption expenditure.\n\n\n##\n\n### Reduced SEM\n\nThus we can obtain the reduced SEM:\n\n$$\n\\begin{cases}\n\\begin{align}\nP_t &= \\pi_{11}+ \\pi_{21}X_t+w_t &&\\text{(eq1)}\\\\\nQ_t &= \\pi_{12}+\\pi_{22}X_t+v_t &&\\text{(eq2)} \\\\\n\\end{align}\n\\end{cases}\n$$\n\nand the relationship between structural and reduced coefficients is:\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n\n$$\n\\begin{cases}\n\\begin{align}\n\\pi_{11} &= \\frac{\\beta_0-\\alpha_0}{\\alpha_1-\\beta_1} \\\\\n\\pi_{21} &= - \\frac{\\alpha_2}{\\alpha_1-\\beta_1}\\\\\nw_t &= \\frac{u_{2t}-u_{t1}}{\\alpha_1-\\beta_1}  \\\\\n\\end{align}\n\\end{cases}\n$$\n\n:::\n\n\n::: {.column width=\"40%\"}\n\n\n$$\n\\begin{cases}\n\\begin{align}\n\\pi_{12} &= \\frac{\\alpha_1\\beta_0-\\alpha_0\\beta_1}{\\alpha_1-\\beta_1}  \\\\\n\\pi_{22} &= - \\frac{\\alpha_2\\beta_1}{\\alpha_1-\\beta_1}  \\\\\nv_t &= \\frac{\\alpha_1u_{t2}-\\beta_1u_{1t}}{\\alpha_1-\\beta_1}\n\\end{align}\n\\end{cases}\n$$\n\n:::\n\n::::\n\n\n##\n\n### Reduced coefficients\n\nFor the above reduced SEM, we can use OLS method to obtain the estimated coefficients:\n\n$$\n\\begin{cases}\n\\begin{align}\n\\widehat{\\pi}_{21} &=  \\frac{\\sum{p_t x_t}}{\\sum{x^2_t}} &&\\text{(slope of the reduced price  eq)} \\\\\n\\widehat{\\pi}_{11} &= \\overline{P} - \\widehat{\\pi}_1 \\cdot \\overline{X} &&\\text{(intercept of the  reduced price eq)} \\\\\n\\widehat{\\pi}_{22} &= \\frac{\\sum{q_t x_t}}{\\sum{x^2_t}} &&\\text{(slope of the reduced quantaty  eq)} \\\\\n\\widehat{\\pi}_{12} &= \\overline{Q} - \\widehat{\\pi}_3 \\cdot \\overline{X} &&\\text{(intercept of the reduced quantaty  eq)}\n\\end{align}\n\\end{cases}\n$$\n\n\n##\n\n### Structural coefficients\n\nBecause we already know that **the supply equation** in the structural SEM is **Just identification** (please review the order and rank conditions) , hence the structural coefficients of the supply equation can be  calculated uniquely with the reduced coefficients.\n\n$$\n\\begin{cases}\n\\begin{align}\n\\beta_0 &= \\pi_{12}+ \\beta_1 \\pi_{11} \\\\\n\\beta_1 &= \\frac{\\pi_{22}}{\\pi_{21}} \\\\\n\\end{align}\n\\end{cases}\n$$\n\nwhich is:\n\n$$\n\\begin{cases}\n\\begin{align}\n\\hat{\\beta_0} &= \\widehat{\\pi}_{12}+ \\hat{\\beta_1} \\widehat{\\pi}_{11} \\\\\n\\hat{\\beta_1} &= \\frac{\\widehat{\\pi}_{22}}{\\widehat{\\pi}_{21}} \\\\\n\\end{align}\n\\end{cases}\n$$\n\n::: {.notes}\n因为我们已经知道（请复习阶条件和秩条件）**供给方程**是**恰好可识别的**，因此供给方程的结构系数是可以由简约系数唯一地估计得到：\n:::\n\n\n##\n\n### OLS estimates for reduced equation\n\nNext, we carry out OLS regression for the reduced equation.\n\n$$\n\\begin{cases}\n\\begin{align}\nP_t &= \\pi_{11}+ \\pi_{21}X_t+w_t &&\\text{(reduced eq1)}\\\\\nQ_t &= \\pi_{12}+\\pi_{22}X_t+v_t &&\\text{(reduced eq2)} \\\\\n\\end{align}\n\\end{cases}\n$$\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n\nThe regression result of the reduced price  equation is:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{P}=&&+90.96&&+0.00X_i\\\\ \n&(s)&&(4.0517)&&(0.0002)\\\\ \n&(t)&&(+22.45)&&(+3.01)\\\\ \n&(fit)&&R^2=0.2440&&\\bar{R}^2=0.2170\\\\ \n&(Ftest)&&F^*=9.04&&p=0.0055\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n:::\n\n\n::: {.column width=\"40%\"}\n\n\nThe regression result of the reduced quantity  equation is:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Q}=&&+59.76&&+0.00X_i\\\\ \n&(s)&&(1.5600)&&(0.0001)\\\\ \n&(t)&&(+38.31)&&(+20.93)\\\\ \n&(fit)&&R^2=0.9399&&\\bar{R}^2=0.9378\\\\ \n&(Ftest)&&F^*=437.95&&p=0.0000\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n:::\n\n::::\n\n\n##\n\n### Obtain structural coefficients\n\nwe can obtain the **reduced coefficients**:\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n- $\\widehat{\\pi}_{21}=$\n0.00074\n\n- $\\widehat{\\pi}_{11}=$\n90.96007\n\n:::\n\n\n::: {.column width=\"40%\"}\n\n- $\\widehat{\\pi}_{22}=$\n0.00197\n\n- $\\widehat{\\pi}_{12}=$\n59.76183\n:::\n\n::::\n\nBecause **supply equation** in structural SEM is **Just identification**, so the structural coefficients of **supply equation** can be calculated by using the estimated reduced coefficients.\n\n\n  $\\hat{\\beta_1} = \\frac{\\widehat{\\pi}_{22}}{\\widehat{\\pi}_{12}}$  =\n0.00197 /\n0.00074 =\n2.68052\n  $\\hat{\\beta_0} = \\widehat{\\pi}_{12}+ \\hat{\\beta_1} \\widehat{\\pi}_{11}$  =\n59.76183 -\n2.68052 $\\cdot$\n90.96007 =\n-184.05874\n\n\nTherefore, the ILS estimators of **supply equation** parameters are:\n\n  $\\hat{Q_t}=$ \n-184.05874 +\n2.68052  $P_t$ \n\n\n\n##\n\n### Result comparison\n\nAs comparison, we will show a **\"biased\"** estimation method, which  use  OLS directly for both quantity and price equation.\n\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n\n- Estimation of the **supply equation** based on the ILS approach:\n  $\\hat{Q_t}=$ \n-184.05874 +\n2.68052  $P_t$ \n\n:::\n\n::: {.column width=\"10\"}\n\n:::\n\n::: {.column width=\"40%\"}\n\n- Estimation of the **supply equation** based on the **biased** OLS approach:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Q}=&&+20.89&&+0.67P_i\\\\ \n&(s)&&(23.0396)&&(0.2246)\\\\ \n&(t)&&(+0.91)&&(+2.99)\\\\ \n&(fit)&&R^2=0.2425&&\\bar{R}^2=0.2154\\\\ \n&(Ftest)&&F^*=8.96&&p=0.0057\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n:::\n\n::::\n\n\n# 20.4 Two-stage least square method (2SLS){#TSLS .monash-bg-blue .mcenter}\n\n## 2SLS with Overidentification model\n\n<!-- insert image here -->\n\n##\n\n### Structural SEM\n\nConsider the following structural SEM:\n\n$$\n\\begin{cases}\n\\begin{alignat}{6}\nY_{t1} = & &+ \\gamma_{21}Y_{2t} & & +\\beta_{01}  & + \\beta_{11}X_{t1} & + \\beta_{21}X_{t2}  &  +u_{t1} & \\text{   (income eq)} \\\\\nY_{t2} =  & + \\gamma_{12}Y_{t1} & &  &    +\\beta_{02} & & & + u_{t2} & \\text{   (monetary supply eq)}\n\\end{alignat}\n\\end{cases}\n$$\n\nwhere:  $Y_1=$ Income;  $Y_2=$ Monetary stock;  $X_1=$ Government expenditure;  $X_2=$ Government spending on goods and services\n\nUsing **order condition rules** and **rank condition rules** (Review), we can know:\n\n- The **Income equation** is **underidentification**\n- if you don't change the model specification, then god can't help you!\n\n- The **monetary supply equation** is **overidentification**\nit's easy to prove that if we apply the ILS approach we will obtain two estimates on  $\\gamma_{21}$ . Hence it is impossible to determin the exact value.\n\n::: {.notes}\n运用**阶条件识别规则**和**秩条件识别规则**（复习），可以知道：- **收入方程**是**不可识别的**- 如果不改变模型设定，那“神也帮不了你”！- **货币供给方程**是**过度识别的**- 容易证明，如果采用ILS估计方法，$\\gamma_{21}$有两个ILS估计值。所以也没办法估计得到！\n:::\n\n\n##\n\n### Instrument variables\n\nLooking for **Instrument variables approach** to crack the **overidentification** problems:\n\n- In practice, people might want to use OLS to estimate the monetary supply equation, but it will get the biased estimators, because there exist correlationship between  $Y_1$  and  $u_2$ .\n\n> **Instrument Variable**: An agent variable which is highly correlated with  $Y_1$  but have no relationship with  $u_2$ .\n\n\n- if we can find an **instrument variable**, then we can apply  OLS approach directly to estimate the structural monetary supply eqution.\n\nBut how does one obtain such an instrumental variable?\n\nOne answer is provided by the **two-stageleast squares** (2SLS), developed independently by Henri Theil and Robert Basmann.\n\n::: {.notes}\n由瑟尔和巴斯曼 (Robert Basmann)各自独立发现的两阶段最小二乘 (two-stage least squares, 2SLS)成为寻找合适**工具变量**的重要方途径和方法。\n:::\n\n\n##\n\n### Stage 1 of 2SLS\n\n**2SLS method** involves two successive applications of OLS. The process is as follows:\n\n\n**Stage 1**. To get rid of the likely correlation between  $Y_1$  and  $u_2$ ,apply regresssion  $Y_1$  on all the predetermined variables in the whole system, not just that equation.\n\n$$\n\\begin{align}\nY_{t1} &= \\widehat{\\pi}_{01} + \\widehat{\\pi}_{11} X_{t1} +  \\widehat{\\pi}_{21} X_{t2} + \\hat{v}_{t1} \\\\\n&= \\hat{Y_{t1} } + \\hat{v}_{t1} \\\\\n\\hat{Y_{t1} }&= \\widehat{\\pi}_{01} + \\widehat{\\pi}_{11} X_{t1} +  \\widehat{\\pi}_{21} X_{t2}\n\\end{align}\n$$\n\nIndicates that the random  $Y_1$  is composed of two parts:\n\n- a linear combination of the nonstochastic  $X$\n- random component  $\\hat{u}_t$ \n\n>according to OLS theory,  $\\hat {Y}_{t1}$  is not related to  $\\hat{v}_{t1}$  (Why?).\n\n\n\n::: {.notes}\n**stage 1: **为摆脱  $Y_1$  和  $u_2$  之间可能的相关性，先求  $Y_1$ 对整个方程组(不仅仅是所考虑的方程中)全部**前定变量**的回归。也即：表明随机的  $Y_1$ 是由两部分构成：- 随机X的一个线性组合而成的  $\\hat{Y}_{t1}$  - 随机成分  $\\hat{u}_t$  - 按照OLS理论，  $\\hat{Y}_{t1}$  与  $\\hat{v}_{t1}$ 是不相关的（Why？提问）。\n:::\n\n\n##\n\n### Stage 2 of 2SLS\n\n**stage 2**. Now retransform the **overidentification** supply equation as follow:\n\n$$\n\\begin{align}\nY_{t2} & = \\beta_{02}  + \\gamma_{12} Y_{t1} + u_{t2}  \\\\\n& = \\beta_{02}  + \\gamma_{12} (\\hat{Y}_{t1}+\\hat{v}_{t1}) + u_{t2} \\\\\n& = \\beta_{02}  + \\gamma_{12} \\hat{Y}_{t1}+(\\gamma_{12} \\hat{v}_{t1} + u_{t2} ) \\\\\n& = \\beta_{02}  + \\gamma_{12} \\hat{Y}_{t1}+ u_{t2}^{\\ast}\n\\end{align}\n$$\n\nWe can prove that:\n\n- the variable  $Y_{t1}$  may be relative with the disturbance term  $u_{t2}$ , which will invalid the OLS approach.\n\n- Meanwhile,  $\\hat{Y_{1t}}$ is uncorrelated with  $u_{t2}^{\\ast}$  asymptotically, that is, in the large sample (or more accurately, as the sample size increases indeﬁnitely).\n\n> As a result, OLS can be applied to monetary Eq, which will give consistent estimates of the parameters of the monetary supply function.\n\n\n##\n\n### 2SLS Features (1/4)\n\nNote the following features of 2SLS:\n\n- It can be applied to an individual equation in the system without directly taking into account any other equation(s) in the system. Hence, for solving econometric models involving a large number of equations, 2SLS offers an economical method.\n\n- Unlike ILS, which provides multiple estimates of parameters in the overidentiﬁed equations, 2SLS provides only one estimate per parameter.\n\n- It is easy to apply because all one needs to know is the total number of exogenous or pre-determined variables in the system without knowing any other variables in the system.\n\n- Although specially designed to handle overidentiﬁed equations, the method can also be applied to exactly identiﬁed equations. But then ILS and 2SLS will give identical estimates. (Why?)\n\n\n::: {.notes}\n两阶段最小二乘法(2SLS方法)的特点：- 它可以应用于方程组中的某个方程而无需考虑方程组中的其他方程。因此，在求解涉及大量方程的计量经济模型时，2SLS提供了一个经济适用的方法。由于这一原因，此法在实际中被广泛应用。- 相对于ILS为过度识别的方程提供参数的多个估计值，而2SLS对每个参数只提供一个估计值。- 它只需知道方程组中一共有多少个外生或前定变量，而无需知道方程组中的任何其他变量，故易于应用。\n:::\n\n\n##\n\n### 2SLS Features (2/4)\n\nNote the following features of 2SLS (continue):\n\n- If the  $R^2$  values in the reduced-form regressions (that is, Stage 1 regressions) are very high, say, in excess of 0.8, the classical OLS estimates and 2SLS estimates will be very close.\n\n> But this result should not be surprising because if the  $R^2$  value in the first stage is very high, it means that the estimated values of the endogenous variables are very close to their actual values.\n\n> And hence the latter are less likely to be correlated with the stochastic disturbances in the original structural SEM. (Why?)\n\n\n::: {.notes}\n两阶段最小二乘法(2SLS方法)的特点(续)：- 此法虽然专为过度识别的方程而设计，但同样适用于恰好识别的方程。但这时ILS和2SLS将给出相同的估计。(为什么?)- 如果约简型回归（即阶段1的回归）的F值很高，比如说高于0.8。则经典OLS估计和 2SLS估计将相差无几。- 在ILS方法的回归报告中，我们没有给出所估系数的**标准误**，但我们能对 2SLS估计值给出这些**标准误**。\n:::\n\n\n##\n\n### 2SLS Features (3/4)\n\nNote the following features of 2SLS (continue):\n\n- Notice that in reporting the ILS regression we did not state the **standard errors** of the estimated coefﬁcients . But we can do this for the 2SLS estimates because the structural coefﬁcients are directly estimated from the second-stage (OLS) regressions.\n> The estimated standard errors in the second-stage regressions need to be modiﬁed because the error term  $u^{\\ast}_t$  is, in fact, equal to  $u_{2t}+β_{21}\\hat{u}_t$ .\n\n> Hence, the variance of  $u^{\\ast}_t$  is not exactly equal to the variance of the original  $u_{2t}$ .\n\n\n##\n\n### 2SLS Features (4/4)\n\nNote the following features of 2SLS (continue):\n\n- Remarks from `Henri Theil`:\n\n>\n- The statistical justification of the 2SLS is of the large-sample type.\n\n>\n- When the equation system contains lagged endogenous variables, the consistency and large-sample normality of the 2SLS coefﬁcient estimators require an additional condition.\n\n>\n- Take cautions when lagged endogenous variables are not really predetermined.\n\n\n##\n\n### Standard error correction: why?\n\nIn the regression report of ILS method, we do not give the **standard error** of the estimated coefficient, but we can give these **standard error** for the estimator of 2SLS.\n\n- Remind  $u^{\\ast}_{t2}=u_{t2}+\\gamma_{12}\\hat{v}_{t1}$ \n\n- It will imply  $u^{\\ast}_{t2} \\neq u_{t2}$ \n, and then we need to calculate the \"correct\" standard error for the purpose of inference.\n\n> For the specific method of error correction, please refer to appendix 20a.2 of the textbook (Damodar Gujarati).\n\n- In the following cases illurtration, we will show the 2SLS estimates **without error correction** and the 2SLS estimates **with error correction** respectively.\n\n\n::: {.notes}\n在ILS方法的回归报告中，我们没有给出所估系数的**标准误**，但我们能对 2SLS估计值给出这些**标准误**。- 需要注意的是：  $u^{\\ast}_{t2}=u_{t2}+\\gamma_{12}\\hat{v}_{t1}$ - 这意味着  $u^{\\ast}_{t2} \\neq u_{t2}$ ，因此需要进行**误差校正**- 误差矫正的具体办法，可以参考教材附录20A.2- 下面的案例展示中，我们将会分别展示**没有误差校正**的2SLS估计和**经过误差矫正**的2SLS估计。\n:::\n\n\n##\n\n### Standard error correction: focus stage 2\n\nThe process for error correction show as below.\n\n- **stage 2:** The regression form of the supply equation is\n\n$$\n\\begin{align}\nY_{t2} & = \\beta_{02}  + \\gamma_{12} Y_{1t} + u_{2t}  \\\\\n& = \\beta_{02}  + \\gamma_{12} (\\hat{Y_{1t}}+\\hat{v}_{t1}) + u_{2t} \\\\\n& = \\beta_{02}  + \\gamma_{12} \\hat{Y_{1t}}+(\\gamma_{12} \\hat{v}_{t1} + u_{t2} ) \\\\\n& = \\beta_{02}  + \\gamma_{12} \\hat{Y_{1t}}+ u_{t2}^{\\ast}\n\\end{align}\n$$\n\n> Where:\n\n> $u^{\\ast}_{t2}=u_{t2}+\\gamma_{12}\\hat{v}_{t1}$\n\n\n##\n\n### Standard error correction: focus stage 2\n\n- **stage 2:** the estimation for the parameter $\\gamma_{12}$ is $\\hat{\\gamma}_{12}$, and its standard error  $s.e_{\\hat{\\gamma}_{12}}$ can be calculated as below.\n\n$$\n\\begin{align}\nY_{t2} & = \\beta_{02}  + \\gamma_{12} \\hat{Y_{1t}}+ u_{t2}^{\\ast}\n\\end{align}\n$$\n\n$$\n\\begin{align}\ns.e_{\\hat{\\gamma}_{21}} & = \\frac{\\hat{\\sigma}^2_{u^{\\ast}_{t2}}}{\\sum{\\hat{y}^2_{t1}}}\\\\\n\\hat{\\sigma}^2_{u^{\\ast}_{t2}} & =\\frac{ \\sum{\\left ( u^{\\ast}_{t2} \\right )^2} }{n-2} = \\frac{ \\sum{\\left (Y_{t2}-\\hat{\\beta}_{02} -\\hat{\\gamma}_{12}\\hat{Y}_{1t} \\right )^2} }{n-2}\n\\end{align}\n$$\n\n\n##\n\n### Standard error correction: results\n\n- In fact, we know  $u^{\\ast}_{t2} \\neq u_{t2}$  , which means  $\\hat{\\sigma}_{u^{\\ast}_{t2}} \\neq \\hat{\\sigma}_{u_{t2}}$ .\n\n- Thus we can obtain  $\\hat{\\sigma}_{u_{t2}}$ .\n\n\n$$\n\\begin{align}\n\\hat{u}_{t2} &= Y_{t2} - \\hat{\\beta}_{02} - \\hat{\\gamma}_{12}Y_{t1} \\\\\n\\hat{\\sigma}^2_{u_{2t}} & =\\frac{ \\sum{\\left ( u_{2t} \\right )^2} }{n-2} = \\frac{ \\sum{\\left (Y_{t2}-\\hat{\\beta}_{02} -\\hat{\\gamma}_{12}Y_{1t} \\right )^2} }{n-2}\n\\end{align}\n$$\n\n\n##\n\n### Standard error correction: for coefficients\n\nTherefore, in order to correct the standard error of the coefficients estimated by **stage 2** regression, it is necessary to multiply the standard error of each coefficient by the following **error correction factor**.\n\n\n$$\n\\begin{align}\n\\eta &= \\frac{ \\hat{\\sigma}^2_{u_{t2}} } {\\hat{\\sigma}^2_{u^{\\ast}_{t2}} }\n\\end{align}\n$$\n\n$$\n\\begin{align}\ns.e^{\\ast}_{\\hat{\\gamma}_{12}} & = s.e_{\\hat{\\gamma}_{12}} \\cdot \\eta = s.e_{\\hat{\\gamma}_{12}} \\cdot \\frac{ \\hat{\\sigma}^2_{u_{t2}} } {\\hat{\\sigma}^2_{u^{\\ast}_{t2}} } \\\\\ns.e^{\\ast}_{\\hat{\\beta}_{02}} & = s.e_{\\hat{\\beta}_{02}} \\cdot \\eta = s.e_{\\hat{\\beta}_{20}} \\cdot \\frac{ \\hat{\\sigma}^2_{u_{t2}} } {\\hat{\\sigma}^2_{u^{\\ast}_{t2}} }\n\\end{align}\n$$\n\n::: {.notes}\n- **误差矫正因子**：因此校正**stage 2** 回归所估计的系数的标准误，需要对每一个系数的标准误乘以如下的**误差矫正因子**\n:::\n\n\n## Case study and application for 2SLS approach\n\n<!-- insert image here -->\n\n##\n\n### variable description\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-ec0b001c6f1544ffdd7d\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-ec0b001c6f1544ffdd7d\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Variables description<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],[\"Y1\",\"Y2\",\"X1\",\"X2\",\"Y1.l1\",\"Y2.l1\",\"X3\"],[\"GDP:  gross domestic product\",\"M2:money supply\",\"GDPI: Total private domestic investment \",\"FEDEXP: Federal expenditure \",\"GDP_t-1: The gross domestic product of the previous period\",\"M2_t-1: The money supply in the previous period\",\"TB6: 6 month Treasury bond interest rate \"],[\"($1 billion in 2000)\",\"($1 billion)\",\"($1 billion in 2000)\",\"($1 billion)\",\"($1 billion in 2000)\",\"($1 billion)\",\"(%)\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>vars<\\/th>\\n      <th>label<\\/th>\\n      <th>note<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":7,\"rownames\":false,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"vars\",\"targets\":1},{\"name\":\"label\",\"targets\":2},{\"name\":\"note\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[7,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n##\n\n### data set\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-de9ca0af574425b3bb0e\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-de9ca0af574425b3bb0e\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Sample data ( n=36)<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\"],[\"1970 \",\"1971 \",\"1972 \",\"1973 \",\"1974 \",\"1975 \",\"1976 \",\"1977 \",\"1978 \",\"1979 \",\"1980 \",\"1981 \",\"1982 \",\"1983 \",\"1984 \",\"1985 \",\"1986 \",\"1987 \",\"1988 \",\"1989 \",\"1990 \",\"1991 \",\"1992 \",\"1993 \",\"1994 \",\"1995 \",\"1996 \",\"1997 \",\"1998 \",\"1999  \",\"2000 \",\"2001 \",\"2002\",\"2003\",\"2004 \",\"2005 \"],[3771.9,3898.6,4105,4341.5,4319.6,4311.2,4540.9,4750.5,5015,5173.4,5161.7,5291.7,5189.3,5423.8,5813.6,6053.7,6263.6,6475.1,6742.7,6981.4,7112.5,7100.5,7336.6,7532.7,7835.5,8031.7,8328.9,8703.5,9066.9,9470.299999999999,9817,9890.700000000001,10048.8,10301,10703.5,11048.6],[626.5,710.3,802.3,855.5,902.1,1016.2,1152,1270.3,1366,1473.7,1599.8,1755.4,1910.3,2126.5,2310,2495.7,2732.4,2831.4,2994.5,3158.5,3278.6,3379.1,3432.5,3484,3497.5,3640.4,3815.1,4031.6,4379,4641.1,4920.9,5430.3,5774.1,6062,6411.7,6669.4],[427.1,475.7,532.1,594.4,550.6,453.1,544.7,627,702.6,725,645.3,704.9,606,662.5,857.7,849.7,843.9,870,890.5,926.2,895.1,822.2,889,968.3,1099.6,1134,1234.3,1387.7,1524.1,1642.6,1735.5,1598.4,1557.1,1613.1,1770.6,1866.3],[201.1,220,244.4,261.7,293.3,346.2,374.3,407.5,450,497.5,585.7,672.7,748.5,815.4,877.1,948.2,1006,1041.6,1092.7,1167.5,1253.5,1315,1444.6,1496,1533.1,1603.5,1665.8,1708.9,1734.9,1787.6,1864.4,1969.5,2101.1,2252.1,2383,2555.9],[null,3771.9,3898.6,4105,4341.5,4319.6,4311.2,4540.9,4750.5,5015,5173.4,5161.7,5291.7,5189.3,5423.8,5813.6,6053.7,6263.6,6475.1,6742.7,6981.4,7112.5,7100.5,7336.6,7532.7,7835.5,8031.7,8328.9,8703.5,9066.9,9470.299999999999,9817,9890.700000000001,10048.8,10301,10703.5],[null,626.5,710.3,802.3,855.5,902.1,1016.2,1152,1270.3,1366,1473.7,1599.8,1755.4,1910.3,2126.5,2310,2495.7,2732.4,2831.4,2994.5,3158.5,3278.6,3379.1,3432.5,3484,3497.5,3640.4,3815.1,4031.6,4379,4641.1,4920.9,5430.3,5774.1,6062,6411.7]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>year<\\/th>\\n      <th>Y1<\\/th>\\n      <th>Y2<\\/th>\\n      <th>X1<\\/th>\\n      <th>X2<\\/th>\\n      <th>Y1.l1<\\/th>\\n      <th>Y2.l1<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"tip\",\"pageLength\":8,\"rownames\":false,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"year\",\"targets\":1},{\"name\":\"Y1\",\"targets\":2},{\"name\":\"Y2\",\"targets\":3},{\"name\":\"X1\",\"targets\":4},{\"name\":\"X2\",\"targets\":5},{\"name\":\"Y1.l1\",\"targets\":6},{\"name\":\"Y2.l1\",\"targets\":7}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[8,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n\n##  Modeling scenario 1 and 2SLS without error correction\n\nOnly the money supply equation is overidentifiable\n\n<!-- insert image here -->\n\n##\n\n### Structural SEM and identification problems\n\nTherefore, we can construct the following structural SEM:\n\n$$\n\\begin{cases}\n\\begin{alignat}{6}\nY_{t1} = \\beta_{01} & &+ \\gamma_{21}Y_{t2} & & + \\beta_{11}X_{t1} & + \\beta_{21}X_{t2}  & & +u_{t1} && \\text{   (income eq)} \\\\\nY_{t2} = \\beta_{02} & + \\gamma_{12}Y_{1t} & &  &  &  & & + u_{t2} && \\text{   (money supply eq)}\n\\end{alignat}\n\\end{cases}\n$$\n\nWhere:\n\n- $Y_1=GDP$ (gross domestic product GDP);\n\n- $Y_2=M2$ (money supply);\n\n- $X_1=GDPI$ (Private domestic investment);\n\n- $X_2=FEDEXP$ (Federal expenditure)\n\n\n\n##\n\n### Stage 1 of 2SLS: fit the reduced equation 1\n\n\n$$\n\\begin{cases}\n\\begin{alignat}{6}\nY_{t1} &&= \\beta_{01} && &&+ \\gamma_{21}Y_{t2} && + \\beta_{11}X_{t1} && + \\beta_{21}X_{t2}  && +u_{t1} && \\text{   (income eq)} \\\\\nY_{t2} &&= \\beta_{02} && + \\gamma_{12}Y_{1t} &&  && && && + u_{t2} && \\text{   (money supply eq)}\n\\end{alignat}\n\\end{cases}\n$$\n\n**stage 1: ** Estimate the regression of  $Y_1$  to all **predetermined variables** in the structural SEM (not only in the equation under consideration), and obtain  $\\hat{Y}_{t1}; \\hat {n} _ {t1}$ .\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\nThat is:\n\n$$\n\\begin{align}\nY_{1t} &= \\widehat{\\pi_0} + \\widehat{\\pi_1} X_{1t} +  \\widehat{\\pi_2} X_{2t} + \\hat{v}_{t1} \\\\\n&= \\hat{Y_{1t} } + \\hat{v}_{t1}\n\\end{align}\n$$\n\n:::\n\n\n::: {.column width=\"40%\"}\n\nRegression results of **stage 1**:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Y1}=&&+2689.85&&+1.87X1_i&&+2.03X2_i\\\\ \n&(s)&&(67.9874)&&(0.1717)&&(0.1075)\\\\ \n&(t)&&(+39.56)&&(+10.89)&&(+18.93)\\\\ \n&(fit)&&R^2=0.9964&&\\bar{R}^2=0.9962 &&\\\\ \n&(Ftest)&&F^*=4534.36&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n:::\n\n::::\n\n\n::: {.notes}\n**stage 1: **先求$Y_1$对整个方程组(不仅仅是所考虑的方程中)全部**前定变量**的回归，并分别得到$\\hat{Y }_{t1} ;\\hat{v}_{t1}$。也即：\n:::\n\n\n##\n\n### stage 1 of 2SLS: fitted $\\hat{Y}_1$ and $\\hat{v}_1$\n\nAt the same time, we can obtain  $\\hat{Y }_{t1} ;\\hat{v}_{t1}$ :\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-3e16d40a423442b44ca5\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3e16d40a423442b44ca5\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>New variable Yt1.hat and vt1.hat after regression of stage 1 <\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\"],[\"1970 \",\"1971 \",\"1972 \",\"1973 \",\"1974 \",\"1975 \",\"1976 \",\"1977 \",\"1978 \",\"1979 \",\"1980 \",\"1981 \",\"1982 \",\"1983 \",\"1984 \",\"1985 \",\"1986 \",\"1987 \",\"1988 \",\"1989 \",\"1990 \",\"1991 \",\"1992 \",\"1993 \",\"1994 \",\"1995 \",\"1996 \",\"1997 \",\"1998 \",\"1999  \",\"2000 \",\"2001 \",\"2002\",\"2003\",\"2004 \",\"2005 \"],[3771.9,3898.6,4105,4341.5,4319.6,4311.2,4540.9,4750.5,5015,5173.4,5161.7,5291.7,5189.3,5423.8,5813.6,6053.7,6263.6,6475.1,6742.7,6981.4,7112.5,7100.5,7336.6,7532.7,7835.5,8031.7,8328.9,8703.5,9066.9,9470.299999999999,9817,9890.700000000001,10048.8,10301,10703.5,11048.6],[626.5,710.3,802.3,855.5,902.1,1016.2,1152,1270.3,1366,1473.7,1599.8,1755.4,1910.3,2126.5,2310,2495.7,2732.4,2831.4,2994.5,3158.5,3278.6,3379.1,3432.5,3484,3497.5,3640.4,3815.1,4031.6,4379,4641.1,4920.9,5430.3,5774.1,6062,6411.7,6669.4],[427.1,475.7,532.1,594.4,550.6,453.1,544.7,627,702.6,725,645.3,704.9,606,662.5,857.7,849.7,843.9,870,890.5,926.2,895.1,822.2,889,968.3,1099.6,1134,1234.3,1387.7,1524.1,1642.6,1735.5,1598.4,1557.1,1613.1,1770.6,1866.3],[201.1,220,244.4,261.7,293.3,346.2,374.3,407.5,450,497.5,585.7,672.7,748.5,815.4,877.1,948.2,1006,1041.6,1092.7,1167.5,1253.5,1315,1444.6,1496,1533.1,1603.5,1665.8,1708.9,1734.9,1787.6,1864.4,1969.5,2101.1,2252.1,2383,2555.9],[null,3771.9,3898.6,4105,4341.5,4319.6,4311.2,4540.9,4750.5,5015,5173.4,5161.7,5291.7,5189.3,5423.8,5813.6,6053.7,6263.6,6475.1,6742.7,6981.4,7112.5,7100.5,7336.6,7532.7,7835.5,8031.7,8328.9,8703.5,9066.9,9470.299999999999,9817,9890.700000000001,10048.8,10301,10703.5],[null,626.5,710.3,802.3,855.5,902.1,1016.2,1152,1270.3,1366,1473.7,1599.8,1755.4,1910.3,2126.5,2310,2495.7,2732.4,2831.4,2994.5,3158.5,3278.6,3379.1,3432.5,3484,3497.5,3640.4,3815.1,4031.6,4379,4641.1,4920.9,5430.3,5774.1,6062,6411.7],[3897.6136,4026.9427,4182.0464,4333.7391,4316.1193,4241.4135,4469.867,4691.3048,4919.1332,5057.6509,5088.0423,5376.4787,5345.7411,5587.4906,6078.0259,6207.7069,6314.4452,6435.6733,6577.9617,6796.8872,6913.6834,6902.474,7291.0365,7543.8892,7864.8892,8072.4327,8386.728800000001,8761.261,9069.216899999999,9398.016900000001,9727.973,9685.4085,9875.8963,10287.7978,10848.6108,11379.3017],[-125.7136,-128.3427,-77.04640000000001,7.7609,3.4807,69.7865,71.033,59.1952,95.8668,115.7491,73.65770000000001,-84.7787,-156.4411,-163.6906,-264.4259,-154.0069,-50.8452,39.4267,164.7383,184.5128,198.8166,198.026,45.5635,-11.1892,-29.3892,-40.7327,-57.8288,-57.761,-2.3169,72.2831,89.027,205.2915,172.9037,13.2022,-145.1108,-330.7017]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>year<\\/th>\\n      <th>Y1<\\/th>\\n      <th>Y2<\\/th>\\n      <th>X1<\\/th>\\n      <th>X2<\\/th>\\n      <th>Y1.l1<\\/th>\\n      <th>Y2.l1<\\/th>\\n      <th>Y1.hat<\\/th>\\n      <th>v1.hat<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"tip\",\"pageLength\":6,\"rownames\":false,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"year\",\"targets\":1},{\"name\":\"Y1\",\"targets\":2},{\"name\":\"Y2\",\"targets\":3},{\"name\":\"X1\",\"targets\":4},{\"name\":\"X2\",\"targets\":5},{\"name\":\"Y1.l1\",\"targets\":6},{\"name\":\"Y2.l1\",\"targets\":7},{\"name\":\"Y1.hat\",\"targets\":8},{\"name\":\"v1.hat\",\"targets\":9}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[6,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n##\n\n### Stage 2 of 2SLS: result of estimation for $Y_2$\n\n$$\n\\begin{cases}\n\\begin{alignat}{6}\nY_{t1} &&= \\beta_{01} && &&+ \\gamma_{21}Y_{t2} && + \\beta_{11}X_{t1} && + \\beta_{21}X_{t2}  && +u_{t1} && \\text{   (income eq)} \\\\\nY_{t2} &&= \\beta_{02} && + \\gamma_{12}Y_{1t} &&  && && && + u_{t2} && \\text{   (money supply eq)}\n\\end{alignat}\n\\end{cases}\n$$\n\n**stage 2:** Now transform the **overidentification** supply equation as follows:\n\n$$\n\\begin{align}\nY_{t2} & = \\beta_{02}  + \\gamma_{12} \\hat{Y}_{1t}+ u_{t2}^{\\ast}\n\\end{align}\n$$\n\n> Using the new variables in **stage 1** results, and apply OLS estimation to obtain:\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Y2}=&&-2440.20&&+0.79Y1.hat_i\\\\ \n&(s)&&(127.3738)&&(0.0178)\\\\ \n&(t)&&(-19.16)&&(+44.52)\\\\ \n&(fit)&&R^2=0.9831&&\\bar{R}^2=0.9826\\\\ \n&(Ftest)&&F^*=1982.40&&p=0.0000\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n\n##\n\n### Comparison (1/2): OLS approach directly\n\nAs comparison, we give a **\"biased\"** estimation with OLS method directly to the money supply equation, and obtain following result:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Y2}=&&-2430.34&&+0.79Y1_i\\\\ \n&(s)&&(127.2148)&&(0.0178)\\\\ \n&(t)&&(-19.10)&&(+44.51)\\\\ \n&(fit)&&R^2=0.9831&&\\bar{R}^2=0.9826\\\\ \n&(Ftest)&&F^*=1980.77&&p=0.0000\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n::: {.notes}\n作为对比，我们给出一个**\"有偏误\"**的估计方法，也即直接对数量$Y2$对$Y1$采用OLS方法，将得到如下结果：\n:::\n\n##\n\n### Comparison (2/2): Raw R report\n\nThe R raw report for the biased regression show as:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = models_money$mod.ols, data = us_money_new)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-418.3 -151.7   40.2  143.5  380.8 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2.430e+03  1.272e+02  -19.10   <2e-16 ***\nY1           7.905e-01  1.776e-02   44.51   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 229.1 on 34 degrees of freedom\nMultiple R-squared:  0.9831,\tAdjusted R-squared:  0.9826 \nF-statistic:  1981 on 1 and 34 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n## Modeling scenario 2\n\nboth income equation and money supply equation are over-identifiable\n\n<!-- insert image here -->\n\n##\n\n### Improved structural SEM and identification problems\n\nDifferent from the former structural SEM, we can construct the improved one:\n\n$$\n\\begin{cases}\n\\begin{alignat}{6}\nY_{t1} = \\beta_{01} & &+ \\gamma_{12}Y_{t2} & & + \\beta_{11}X_{t1} & + \\beta_{21}X_{t2} & & & +u_{t1} & \\text{   (income eq)} \\\\\nY_{t2} = \\beta_{02} & + \\gamma_{12}Y_{1t} & &  &  & &+ \\beta_{12}Y_{1,t-1}  &+ \\beta_{22}Y_{2,t-1} & + u_{t2} & \\text{   (money supply eq)}\n\\end{alignat}\n\\end{cases}\n$$\n\nNext, we judge the identification problem according to **order condition rules 2** :\n\n- The number of predetermineed variables in the structural SEM is  $K=5$ .\n\n- The first equation: the number of predetermined variables is  $k=3$ , and  $(K-k)=2$ . Also the number of endogenous variables is  $m=2$ , and  $(m-1)=1$ . We will see  $(K-k)>(m-1)$ . So the first equation is **overidentification**. \n\n-  The second equation: the number of predetermined variables is  $k=3$ , and  $(K-k)=2$ ; Also the number of endogenous variables is  $m=2$ , and  $(m-1)=1$ . We will see  $(K-k)>(m-1)$ . Thus it is also **overidentification**.\n\n\n::: {.notes}\n- Conclusion: both the income equation and the money supply equation are **overidentifiable**.\n:::\n\n##\n\n### Stage 1 of 2SLS: reduced equation 1 and 2\n\n\nNow, we will use two-stage least squares (2SLS) to get **consistent  estimates** for both **income equation** and **money supply equation**.\n\n\n**Stage 1**:\n\n- Estimate the regression of  $Y_1$  to all **predetermined variables** in the structural SEM (not only in the equation under consideration), and obtain  $\\hat{Y}_{t1} ;\\hat{v}^{\\ast}_{t1}$ .\n\n- [Meanwhile]{.red}, estimate the regression of  $Y_2$  to all **predetermined variables** in the structural SEM (not only in the equation under consideration), and obtain  $\\hat{Y}_{t2} ;\\hat{v}^{\\ast}_{t2}$ ：\n\n$$\n\\begin{align}\nY_{t1} &= \\widehat{\\pi}_{01} + \\widehat{\\pi}_{11} X_{t1} +  \\widehat{\\pi}_{21} X_{t2} +  \\widehat{\\pi}_{31} Y_{t-1,1} +  \\widehat{\\pi}_{41} Y_{t-1,2}+ \\hat{v}_{t1} \\\\\n&= \\hat{Y}_{1t} +\\hat{v}_{t1} \\\\\nY_{t2} &= \\widehat{\\pi}_{02} + \\widehat{\\pi}_{12} X_{t1} +  \\widehat{\\pi}_{22} X_{t2} +  \\widehat{\\pi}_{32} Y_{t-1,1} +  \\widehat{\\pi}_{42} Y_{t-1,2}+ \\hat{v}_{t2} \\\\\n&= \\hat{Y}_{t2} +\\hat{v}_{t2}\n\\end{align}\n$$\n\n\n##\n\n### Stage 1 of 2SLS: fit the reduced equation 1\n\n- OLS regression results of **new income equation** at **stage 1**:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Y1}=&&+1098.90&&+0.98X1_i&&+0.77X2_i\\\\ \n&(s)&&(185.5566)&&(0.1308)&&(0.1831)\\\\ \n&(t)&&(+5.92)&&(+7.50)&&(+4.19)\\\\ \n&(cont.)&&+0.59Y1.l1_i&&-0.01Y2.l1_i &&\\\\ \n&(s)&&(0.0667)&&(0.0721) &&\\\\ \n&(t)&&(+8.87)&&(-0.10) &&\\\\ \n&(fit)&&R^2=0.9990&&\\bar{R}^2=0.9989 &&\\\\ \n&(Ftest)&&F^*=7857.58&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n\n##\n\n### Stage 1 of 2SLS: fit the reduced equation 2\n\n- OLS regression results of **new money supply equation** at **stage 1**:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Y2}=&&-207.14&&+0.20X1_i&&-0.35X2_i\\\\ \n&(s)&&(184.9121)&&(0.1303)&&(0.1824)\\\\ \n&(t)&&(-1.12)&&(+1.53)&&(-1.95)\\\\ \n&(cont.)&&+0.06Y1.l1_i&&+1.06Y2.l1_i &&\\\\ \n&(s)&&(0.0665)&&(0.0718) &&\\\\ \n&(t)&&(+0.94)&&(+14.78) &&\\\\ \n&(fit)&&R^2=0.9985&&\\bar{R}^2=0.9983 &&\\\\ \n&(Ftest)&&F^*=5050.57&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n\n##\n\n### Stage 1 of 2SLS: fitted $\\hat{Y}_i$ and $\\hat{v}_i$\n\nHence, we can obtain new variables from the two former regressions results respectively:  $\\hat{Y}_{t1} ;\\hat{v}_{t1}$ , and  $\\hat{Y}_{t2} ;\\hat{v}_{t2}$ .\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-c076c3934f62062303c2\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c076c3934f62062303c2\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>New variables from regression of stage 1<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\"],[3771.9,3898.6,4105,4341.5,4319.6,4311.2,4540.9,4750.5,5015,5173.4,5161.7,5291.7,5189.3,5423.8,5813.6,6053.7,6263.6,6475.1,6742.7,6981.4,7112.5,7100.5,7336.6,7532.7,7835.5,8031.7,8328.9,8703.5,9066.9,9470.299999999999,9817,9890.700000000001,10048.8,10301,10703.5,11048.6],[null,3771.9,3898.6,4105,4341.5,4319.6,4311.2,4540.9,4750.5,5015,5173.4,5161.7,5291.7,5189.3,5423.8,5813.6,6053.7,6263.6,6475.1,6742.7,6981.4,7112.5,7100.5,7336.6,7532.7,7835.5,8031.7,8328.9,8703.5,9066.9,9470.299999999999,9817,9890.700000000001,10048.8,10301,10703.5],[null,3963.162218698584,4111.57768515084,4307.472477662284,4428.445789295687,4360.130197240647,4465.651511040218,4706.820541713739,4936.779482855238,5151.10621835138,5233.640666672667,5350.923136373019,5387.954572780171,5432.85464188149,5808.796663922689,6084.983782911466,6264.452717476738,6439.903124230009,6623.715190142633,6873.354063194491,7048.981386430858,7101.445092670142,7258.466794847532,7515.051378346537,7787.964825020155,8054.905880620426,8316.143472795484,8674.287620623134,9048.184887499199,9417.413699973236,9804.350626605637,9953.830372104832,10054.16192368472,10315.95395359625,10717.96558118063,11180.16782240724],[null,-64.56221869858442,-6.577685150839852,34.02752233771594,-108.8457892956865,-48.93019724064735,75.24848895978158,43.67945828626091,78.22051714476243,22.29378164862045,-71.94066667266719,-59.22313637301926,-198.6545727801713,-9.054641881489717,4.803336077311913,-31.28378291146592,-0.8527174767375314,35.19687576999155,118.9848098573668,108.0459368055086,63.51861356914195,-0.9450926701418041,78.1332051524688,17.64862165346311,47.5351749798449,-23.20588062042619,12.75652720451588,29.21237937686628,18.71511250080028,52.8863000267622,12.64937339436234,-63.13037210483236,-5.361923684718152,-14.95395359624757,-14.4655811806273,-131.5678224072434],[626.5,710.3,802.3,855.5,902.1,1016.2,1152,1270.3,1366,1473.7,1599.8,1755.4,1910.3,2126.5,2310,2495.7,2732.4,2831.4,2994.5,3158.5,3278.6,3379.1,3432.5,3484,3497.5,3640.4,3815.1,4031.6,4379,4641.1,4920.9,5430.3,5774.1,6062,6411.7,6669.4],[null,626.5,710.3,802.3,855.5,902.1,1016.2,1152,1270.3,1366,1473.7,1599.8,1755.4,1910.3,2126.5,2310,2495.7,2732.4,2831.4,2994.5,3158.5,3278.6,3379.1,3432.5,3484,3497.5,3640.4,3815.1,4031.6,4379,4641.1,4920.9,5430.3,5774.1,6062,6411.7],[null,709.4576166660944,808.9000750550479,925.7029618627264,976.9543052393032,986.8583813216993,1115.772542775514,1278.874692124581,1417.509348876738,1523.182688425863,1600.19772622861,1714.365020458257,1841.044721267882,1986.663847561975,2247.824349480077,2440.079170127191,2630.51598424703,2887.462426772493,2991.686162899701,3162.078305244926,3314.335880428334,3413.649792017532,3486.934315827488,3555.888081874735,3635.77808162732,3650.82230965648,3812.640252821573,4031.905496701089,4303.046839862698,4699.43221839384,4994.080786204415,5248.098089638751,5738.608277626416,6071.053906034444,6377.36949878321,6731.425845865968],[null,0.842383333905607,-6.600075055047887,-70.20296186272643,-74.85430523930316,29.34161867830068,36.22745722448644,-8.574692124580604,-51.50934887673765,-49.48268842586285,-0.3977262286102476,41.03497954174347,69.25527873211814,139.8361524380255,62.17565051992345,55.62082987280873,101.8840157529697,-56.06242677249317,2.813837100299418,-3.578305244925896,-35.73588042833392,-34.54979201753182,-54.43431582748846,-71.88808187473475,-138.2780816273204,-10.42230965648022,2.459747178427013,-0.3054967010889013,75.95316013730162,-58.33221839384012,-73.18078620441493,182.2019103612492,35.49172237358437,-9.053906034443695,34.33050121678998,-62.02584586596839]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Y1<\\/th>\\n      <th>Y1.l1<\\/th>\\n      <th>Y1.hat<\\/th>\\n      <th>v1.hat<\\/th>\\n      <th>Y2<\\/th>\\n      <th>Y2.l1<\\/th>\\n      <th>Y2.hat<\\/th>\\n      <th>v2.hat<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"tip\",\"pageLength\":6,\"rownames\":false,\"columnDefs\":[{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":8,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":7,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Y1\",\"targets\":1},{\"name\":\"Y1.l1\",\"targets\":2},{\"name\":\"Y1.hat\",\"targets\":3},{\"name\":\"v1.hat\",\"targets\":4},{\"name\":\"Y2\",\"targets\":5},{\"name\":\"Y2.l1\",\"targets\":6},{\"name\":\"Y2.hat\",\"targets\":7},{\"name\":\"v2.hat\",\"targets\":8}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[6,10,25,50,100]}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\",\"options.columnDefs.4.render\",\"options.columnDefs.5.render\",\"options.columnDefs.6.render\",\"options.columnDefs.7.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n##\n\n### Stage 2 of 2SLS: estimate the structural equation 1 and 2\n\n**Stage 2:**\n\n- The re-transformed new income equation and the money supply equation are:\n\n$$\n\\begin{align}\nY_{t1} &= \\beta_{01}  + \\gamma_{21} \\hat{Y}_{t2}  + \\beta_{11}X_{t1}  + \\beta_{21}X_{t2} +u^{\\ast}_{t1}  \\\\\nY_{t2} &= \\beta_{20}  + \\gamma_{12} \\hat{Y}_{1t} + \\beta_{12}Y_{t-1,1}  + \\beta_{22}Y_{t-1,2}  + u^{\\ast}_{t2}\n\\end{align}\n$$\n\n- And then, we can conduct these new equations by using the former variables frome stage 1.\n\n\n##\n\n### Stage 2 of 2SLS: OLS estimation for the new income equation\n\n- OLS estimation results of **new** income equation in **stage 2**:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Y1}=&&+2723.68&&+0.22Y2.hat_i&&+1.71X1_i\\\\ \n&(s)&&(67.5331)&&(0.1156)&&(0.1848)\\\\ \n&(t)&&(+40.33)&&(+1.90)&&(+9.27)\\\\ \n&(cont.)&&+1.57X2_i && &&\\\\ \n&(s)&&(0.2623) && &&\\\\ \n&(t)&&(+5.98) && &&\\\\ \n&(fit)&&R^2=0.9966&&\\bar{R}^2=0.9963 &&\\\\ \n&(Ftest)&&F^*=3073.97&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n\n##\n\n### Stage 2 of 2SLS: OLS estimation for the new money supply equation\n\n- OLS estimation results of the **new** money supply equation in **stage 2**:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Y2}=&&-228.13&&+0.11Y1.hat_i&&-0.03Y1.l1_i\\\\ \n&(s)&&(153.6925)&&(0.1431)&&(0.1481)\\\\ \n&(t)&&(-1.48)&&(+0.77)&&(-0.17)\\\\ \n&(cont.)&&+0.93Y2.l1_i && &&\\\\ \n&(s)&&(0.0618) && &&\\\\ \n&(t)&&(+15.10) && &&\\\\ \n&(fit)&&R^2=0.9981&&\\bar{R}^2=0.9979 &&\\\\ \n&(Ftest)&&F^*=5461.60&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n##\n\n### Stage 2 of 2SLS: Raw R report for the new income equation\n\n- The R raw report of OLS estimation for the  new income equation in **stage 2**:\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = models_money2$mod2.stage2.1, data = us_money_new2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-360.45  -66.79   35.70   81.22  186.18 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 2723.6809    67.5331  40.331  < 2e-16 ***\nY2.hat         0.2192     0.1156   1.896   0.0673 .  \nX1             1.7142     0.1848   9.275 1.87e-10 ***\nX2             1.5690     0.2623   5.981 1.29e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 130.1 on 31 degrees of freedom\n  (因为不存在，1个观察量被删除了)\nMultiple R-squared:  0.9966,\tAdjusted R-squared:  0.9963 \nF-statistic:  3074 on 3 and 31 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n##\n\n### Stage 2 of 2SLS: Raw R report for the new money supply equation\n\n- The R raw report of OLS estimation for the  new money supply equation in **stage 2**:\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = models_money2$mod2.stage2.1, data = us_money_new2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-360.45  -66.79   35.70   81.22  186.18 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 2723.6809    67.5331  40.331  < 2e-16 ***\nY2.hat         0.2192     0.1156   1.896   0.0673 .  \nX1             1.7142     0.1848   9.275 1.87e-10 ***\nX2             1.5690     0.2623   5.981 1.29e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 130.1 on 31 degrees of freedom\n  (因为不存在，1个观察量被删除了)\nMultiple R-squared:  0.9966,\tAdjusted R-squared:  0.9963 \nF-statistic:  3074 on 3 and 31 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n##\n\n### Simultaneous 2SLS approach with error correction automatically (tidy report)\n\nBy using R `systemfit` package, we can apply the two-stage least square method with **\"error correction\"**, and the report summarized as follows:\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-bb7f636abb92b510ef63\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-bb7f636abb92b510ef63\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Result of 2SLS with error correction<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\"],[\"eq1\",\"eq1\",\"eq1\",\"eq1\",\"eq2\",\"eq2\",\"eq2\",\"eq2\"],[\"(Intercept)\",\"Y2\",\"X1\",\"X2\",\"(Intercept)\",\"Y1\",\"Y1.l1\",\"Y2.l1\"],[2723.680943893551,0.2192433223964512,1.714215627653126,1.569038795258533,-228.132038697227,0.1099681798617617,-0.02504161765844515,0.932956220564694],[69.10172904331981,0.1183166047253771,0.1891188525269129,0.2684267712659791,157.9454624202284,0.1470503960203062,0.1522271712584281,0.06351113211180455],[39.41552522059293,1.853022429990562,9.064223924524825,5.845314116242905,-1.444372223180814,0.7478264787983038,-0.1645016290549951,14.68964872051603],[0,0.07341965960582764,3.171689577641246e-10,1.906845800592194e-06,0.1586663999607163,0.4602005929123907,0.8704042154588558,1.77635683940025e-15]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>eq<\\/th>\\n      <th>vars<\\/th>\\n      <th>Estimate<\\/th>\\n      <th>Std. Error<\\/th>\\n      <th>t value<\\/th>\\n      <th>Pr(&gt;|t|)<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":10,\"rownames\":false,\"columnDefs\":[{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"eq\",\"targets\":1},{\"name\":\"vars\",\"targets\":2},{\"name\":\"Estimate\",\"targets\":3},{\"name\":\"Std. Error\",\"targets\":4},{\"name\":\"t value\",\"targets\":5},{\"name\":\"Pr(>|t|)\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n##\n\n### Simultaneous 2SLS approach with error correction automatically (raw report)\n\nBy using R `systemfit` package, we can apply the two-stage least square method with **\"error correction\"**, and the detail report show as follows:\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nsystemfit results \nmethod: 2SLS \n\n        N DF    SSR   detRCov   OLS-R2 McElroy-R2\nsystem 70 62 749260 107381032 0.997082   0.998059\n\n     N DF    SSR      MSE     RMSE       R2   Adj R2\neq1 35 31 549669 17731.24 133.1587 0.996492 0.996153\neq2 35 31 199592  6438.44  80.2399 0.998006 0.997813\n\nThe covariance matrix of the residuals\n         eq1      eq2\neq1 17731.24 -2603.96\neq2 -2603.96  6438.44\n\nThe correlations of the residuals\n         eq1      eq2\neq1  1.00000 -0.24371\neq2 -0.24371  1.00000\n\n\n2SLS estimates for 'eq1' (equation 1)\nModel Formula: Y1 ~ Y2 + X1 + X2\nInstruments: ~X1 + X2 + Y1.l1 + Y2.l1\n\n               Estimate  Std. Error  t value   Pr(>|t|)    \n(Intercept) 2723.680944   69.101729 39.41553 < 2.22e-16 ***\nY2             0.219243    0.118317  1.85302    0.07342 .  \nX1             1.714216    0.189119  9.06422 3.1717e-10 ***\nX2             1.569039    0.268427  5.84531 1.9068e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 133.158716 on 31 degrees of freedom\nNumber of observations: 35 Degrees of Freedom: 31 \nSSR: 549668.549447 MSE: 17731.243531 Root MSE: 133.158716 \nMultiple R-Squared: 0.996492 Adjusted R-Squared: 0.996153 \n\n\n2SLS estimates for 'eq2' (equation 2)\nModel Formula: Y2 ~ Y1 + Y1.l1 + Y2.l1\nInstruments: ~X1 + X2 + Y1.l1 + Y2.l1\n\n                Estimate   Std. Error  t value   Pr(>|t|)    \n(Intercept) -228.1320387  157.9454624 -1.44437    0.15867    \nY1             0.1099682    0.1470504  0.74783    0.46020    \nY1.l1         -0.0250416    0.1522272 -0.16450    0.87040    \nY2.l1          0.9329562    0.0635111 14.68965 1.7764e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 80.239917 on 31 degrees of freedom\nNumber of observations: 35 Degrees of Freedom: 31 \nSSR: 199591.774884 MSE: 6438.444351 Root MSE: 80.239917 \nMultiple R-Squared: 0.998006 Adjusted R-Squared: 0.997813 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n##\n\n### Comparison to OLS approach directly (biased estimation)\n\n- **\"biased\"** OLS estimation results of the income equation:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Y1}=&&+2706.39&&+0.17Y2_i&&+1.75X1_i\\\\ \n&(s)&&(67.6150)&&(0.1115)&&(0.1864)\\\\ \n&(t)&&(+40.03)&&(+1.51)&&(+9.39)\\\\ \n&(cont.)&&+1.68X2_i && &&\\\\ \n&(s)&&(0.2552) && &&\\\\ \n&(t)&&(+6.60) && &&\\\\ \n&(fit)&&R^2=0.9966&&\\bar{R}^2=0.9963 &&\\\\ \n&(Ftest)&&F^*=3139.86&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n- **\"biased\"** OLS estimates of the money supply equation:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Y2}=&&-206.53&&-0.02Y1_i&&+0.10Y1.l1_i\\\\ \n&(s)&&(154.4428)&&(0.1178)&&(0.1252)\\\\ \n&(t)&&(-1.34)&&(-0.14)&&(+0.79)\\\\ \n&(cont.)&&+0.94Y2.l1_i && &&\\\\ \n&(s)&&(0.0622) && &&\\\\ \n&(t)&&(+15.14) && &&\\\\ \n&(fit)&&R^2=0.9981&&\\bar{R}^2=0.9979 &&\\\\ \n&(Ftest)&&F^*=5362.58&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n\n# 20.5 Truffle supply and demand{#truffle .monash-bg-blue .mcenter}\n\n## Case of Truffle supply and demand\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](pic/Truffle-pig.jpg){fig-align='center' width=138}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](pic/Truffle-pig2.jpg){fig-align='center' width=138}\n:::\n:::\n\n\n\n:::\n\n\n::: {.column width=\"40%\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](pic/Truffle-pig4.jpg){fig-align='center' width=342}\n:::\n:::\n\n\n\n:::\n\n::::\n\n\n##\n\n### Variables description\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-824c1cd83570cdea4f8c\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-824c1cd83570cdea4f8c\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>variables description<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\"],[\"P\",\"Q\",\"PS\",\"DI\",\"PF\"],[\"market price of trufﬂes\",\"market quantity of trufﬂes\",\"market price of substitute\",\"disposable income\",\"rental price of trufﬂe-pigs\"],[\"dollar/ounce\",\"ounce\",\"dollar/ounce\",\"dollar/person, monthly\",\"dollar/hour\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>vars<\\/th>\\n      <th>label<\\/th>\\n      <th>measure<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"tip\",\"pageLength\":6,\"rownames\":false,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"vars\",\"targets\":1},{\"name\":\"label\",\"targets\":2},{\"name\":\"measure\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[6,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n::: {.notes}\ncase source: Hill, R. C., W. E. Griffiths and G. C. Lim. Principles of Econometrics 4th Edition  [M], Wiley, 2011. chpt 11refferenc: [PoE with R](https://bookdown.org/ccolonescu/RPoE4/simultaneous-equations-models.html)\n:::\n\n\n##\n\n### Data set\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-5b9c23da9281de00e358\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5b9c23da9281de00e358\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Case data set (n=30)<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\"],[29.64,40.23,34.71,41.43,53.37,38.52,54.33,40.56,67.34999999999999,49.65,58.17,66.87,49.95,64.95,52.68,61.2,80.55,89.94,70.77,57.33,46.23,77.43000000000001,83.01000000000001,70.70999999999999,66.75,76.8,83.7,81,88.44,105.45],[19.89,13.04,19.61,17.13,22.55,6.37,15.02,10.22,23.64,16.12,24.55,18.92,11.94,18.93,12.6,20.49,22.94,21.08,16.68,17.61,16.62,20.99,24.53,19.67,23.29,16.64,20.81,14.95,26.27,20.65],[19.97,18.04,22.36,20.87,19.79,15.98,17.94,17.09,22.72,15.74,24.64,23.7,15.93,23.34,15.21,26.04,22.95,27.1,23.65,20.06,26.38,24.28,26.64,22.65,19.68,23.82,28.98,18.52,28.16,28.43],[2.103,2.043,1.87,1.525,2.709,2.489,2.294,2.196,3.885,3.169,2.623,3.007,3.367,3.29,3.746,3.518,4.381,4.121,3.82,4.398,3.764,4.524,4.815,3.67,4.392,4.603,4.632,4.894,5.125,4.836],[10.52,19.67,13.74,17.95,13.71,24.95,24.17,23.61,19.52,20.03,15.38,22.98,25.76,25.17,25.82,19.31,26.02,29.65,27.45,18,18.87,24.58,25.25,24.24,22.63,27.35,27.8,30.34,24.12,34.01]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>P<\\/th>\\n      <th>Q<\\/th>\\n      <th>PS<\\/th>\\n      <th>DI<\\/th>\\n      <th>PF<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"tip\",\"pageLength\":8,\"rownames\":false,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"P\",\"targets\":1},{\"name\":\"Q\",\"targets\":2},{\"name\":\"PS\",\"targets\":3},{\"name\":\"DI\",\"targets\":4},{\"name\":\"PF\",\"targets\":5}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[8,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n##\n\n### Scatter\n\nThe scatter plot on truffle quantity Q and truffle market price P is given below:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/lecture-20-sem-estimation.rmarkdown/unnamed-chunk-35-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n##\n\n### The structural SEM\n\nGiven the structural SEM:\n\n$$\n\\begin{cases}\n\\begin{align}\nQ_i &= \\alpha_0+\\alpha_1P_i+\\alpha_2PS_i+\\alpha_3DI_i+u_{i1}  &&\\text{(demand function)}\\\\\nQ_i &= \\beta_0+\\beta_1P_i+\\beta_2PF_i+u_{i2}    &&\\text{(supply function)}\n\\end{align}\n\\end{cases}\n$$\n\n\n##\n\n### The reduced SEM\n\nWe can get the reduced SEM:\n\n$$\n\\begin{cases}\n\\begin{align}\nP_i &= \\pi_{01}+ \\pi_{11}PS_i+\\pi_{21}DI_i+\\pi_{31}PF_i+v_{t1}\\\\\nQ_i &= \\pi_{02}+\\pi_{12}PS_t+\\pi_{22}DI_i+\\pi_{32}PF_i+v_{t2}\n\\end{align}\n\\end{cases}\n$$\n\nAlso we obtain the relationship between structural and reduced coefficients:\n\n\n:::: {.columns .font-90}\n\n::: {.column width=\"40%\"}\n\n\n$$\n\\begin{cases}\n\\begin{align}\n& \\pi_{01} = \\frac{\\beta_0-\\alpha_0}{\\alpha_1-\\beta_1}  \\\\\n& \\pi_{11} = - \\frac{\\alpha_2}{\\alpha_1-\\beta_1}  \\\\\n& \\pi_{21} = - \\frac{\\alpha_3}{\\alpha_1-\\beta_1}  \\\\\n& \\pi_{31} = \\frac{\\beta_2}{\\alpha_1-\\beta_1}  \\\\\n& v_{t1} = \\frac{u_{2t}-u_{1t}}{\\alpha_1-\\beta_1} &&\n\\end{align}\n\\end{cases}\n$$\n\n:::\n\n\n::: {.column width=\"40%\"}\n\n\n$$\n\\begin{cases}\n\\begin{align}\n& \\pi_{02} = - \\frac{\\alpha_1\\beta_0-\\alpha_0\\beta_1}{\\alpha_1-\\beta_1} \\\\\n& \\pi_{12} = - \\frac{\\alpha_2\\beta_1}{\\alpha_1-\\beta_1}  \\\\\n& \\pi_{22} = - \\frac{\\alpha_3\\beta_1}{\\alpha_1-\\beta_1}  \\\\\n& \\pi_{32} =   \\frac{\\alpha_1\\beta_2}{\\alpha_1-\\beta_1}  \\\\\n& v_{t2} = \\frac{\\alpha_1u_{2t}-\\beta_1u_{1t}}{\\alpha_1-\\beta_1}\n\\end{align}\n\\end{cases}\n$$\n:::\n\n::::\n\n\n##\n\n### Simple OLS solution: stylized report\n\nWe can  apply OLS method directly. Of course estimation results will be biased.\n\n- stylized results of **bias** OLS estimation  for the demand equation:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Q}=&&+1.09&&+0.02P_i&&+0.71PS_i\\\\ \n&(s)&&(3.7116)&&(0.0768)&&(0.2143)\\\\ \n&(t)&&(+0.29)&&(+0.30)&&(+3.31)\\\\ \n&(cont.)&&+0.08DI_i && &&\\\\ \n&(s)&&(1.1909) && &&\\\\ \n&(t)&&(+0.06) && &&\\\\ \n&(fit)&&R^2=0.4957&&\\bar{R}^2=0.4375 &&\\\\ \n&(Ftest)&&F^*=8.52&&p=0.0004 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n- stylized results of **bias** OLS estimation for the supply equation:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Q}=&&+20.03&&+0.34P_i&&-1.00PF_i\\\\ \n&(s)&&(1.2220)&&(0.0217)&&(0.0764)\\\\ \n&(t)&&(+16.39)&&(+15.54)&&(-13.10)\\\\ \n&(fit)&&R^2=0.9019&&\\bar{R}^2=0.8946 &&\\\\ \n&(Ftest)&&F^*=124.08&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n\n\n### Simple OLS solution: R code (`lm`)\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# set equation systems\neq.D <-formula( Q~P + PS + DI)\neq.S <-formula( Q~P + PF)\n\n# fit using direct `OLS` method\nols.D <- lm(formula = eq.D, data = truffles)\nols.S <- lm(formula = eq.S, data = truffles)\n# estimation summary\nsmry.olsD <- summary(ols.D)\nsmry.olsS <- summary(ols.S)\n```\n:::\n\n\n\n\n\n##\n\n### Simple OLS solution: R report for demand eqation\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = eq.D, data = truffles)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-7.155 -1.936 -0.374  2.396  6.335 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)   \n(Intercept)  1.09105    3.71158   0.294  0.77112   \nP            0.02330    0.07684   0.303  0.76418   \nPS           0.71004    0.21432   3.313  0.00272 **\nDI           0.07644    1.19086   0.064  0.94931   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.46 on 26 degrees of freedom\nMultiple R-squared:  0.4957,\tAdjusted R-squared:  0.4375 \nF-statistic:  8.52 on 3 and 26 DF,  p-value: 0.0004159\n```\n\n\n:::\n:::\n\n\n\n\n##\n\n### Simple OLS solution: R report for supply eqation\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = eq.S, data = truffles)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.7830 -0.8530  0.2270  0.7579  3.3475 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 20.03278    1.22197   16.39 1.47e-15 ***\nP            0.33799    0.02174   15.54 5.42e-15 ***\nPF          -1.00092    0.07639  -13.10 3.23e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.498 on 27 degrees of freedom\nMultiple R-squared:  0.9019,\tAdjusted R-squared:  0.8946 \nF-statistic: 124.1 on 2 and 27 DF,  p-value: 2.448e-14\n```\n\n\n:::\n:::\n\n\n\n\n##\n\n### Simultaneous OLS solution: R code (`symtemfit`)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load pkg\nrequire(systemfit)\n# set equation systems\neq.D <- Q~P + PS + DI\neq.S <- Q~P + PF\neq.sys <- list(eq.D, eq.S)\n# system fit using `OLS` method\nsystem.ols <- systemfit(\n  formula = eq.sys,\n  method = \"OLS\",\n  data = truffles\n)\n# estimation summary\nsmry.ols <- summary(system.ols)\n```\n:::\n\n\n\n\n\n##\n\n### Simultaneous OLS solution: R report (`symtemfit`)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nsystemfit results \nmethod: OLS \n\n        N DF     SSR detRCov   OLS-R2 McElroy-R2\nsystem 60 53 371.764 23.5756 0.698799   0.808917\n\n     N DF      SSR      MSE    RMSE       R2   Adj R2\neq1 30 26 311.2096 11.96960 3.45971 0.495720 0.437534\neq2 30 27  60.5546  2.24276 1.49758 0.901878 0.894610\n\nThe covariance matrix of the residuals\n         eq1     eq2\neq1 11.96960 1.80814\neq2  1.80814 2.24276\n\nThe correlations of the residuals\n        eq1     eq2\neq1 1.00000 0.34898\neq2 0.34898 1.00000\n\n\nOLS estimates for 'eq1' (equation 1)\nModel Formula: Q ~ P + PS + DI\n\n             Estimate Std. Error t value  Pr(>|t|)   \n(Intercept) 1.0910453  3.7115804 0.29396 0.7711247   \nP           0.0232954  0.0768423 0.30316 0.7641812   \nPS          0.7100395  0.2143246 3.31292 0.0027193 **\nDI          0.0764442  1.1908551 0.06419 0.9493078   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.459711 on 26 degrees of freedom\nNumber of observations: 30 Degrees of Freedom: 26 \nSSR: 311.209627 MSE: 11.969601 Root MSE: 3.459711 \nMultiple R-Squared: 0.49572 Adjusted R-Squared: 0.437534 \n\n\nOLS estimates for 'eq2' (equation 2)\nModel Formula: Q ~ P + PF\n\n              Estimate Std. Error  t value   Pr(>|t|)    \n(Intercept) 20.0327764  1.2219720  16.3938 1.3323e-15 ***\nP            0.3379875  0.0217445  15.5435 5.3291e-15 ***\nPF          -1.0009246  0.0763902 -13.1028 3.2352e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.497585 on 27 degrees of freedom\nNumber of observations: 30 Degrees of Freedom: 27 \nSSR: 60.554565 MSE: 2.242762 Root MSE: 1.497585 \nMultiple R-Squared: 0.901878 Adjusted R-Squared: 0.89461 \n```\n\n\n:::\n:::\n\n\n\n\n\n##\n\n### IV 2SLS solution: R code (`symtemfit`)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load pkg\nrequire(systemfit)\n# set equation systems\neq.D <- Q~P + PS + DI\neq.S <- Q~P + PF\neq.sys <- list(eq.D, eq.S)\n# set instruments\ninstr <- ~ PS + DI + PF\n# system fit using `2SLS` method\nsystem.iv <- systemfit(\n  formula = eq.sys, inst = instr,\n  method = \"2SLS\",\n  data = truffles\n)\n# estimation summary\nsmry.iv <- summary(system.iv)\n```\n:::\n\n\n\n\n##\n\n### IV-2SLS Solution:  R report (`symtemfit`)\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nsystemfit results \nmethod: 2SLS \n\n        N DF     SSR detRCov   OLS-R2 McElroy-R2\nsystem 60 53 692.472 49.8028 0.438964   0.807408\n\n     N DF      SSR      MSE    RMSE        R2    Adj R2\neq1 30 26 631.9171 24.30450 4.92996 -0.023950 -0.142098\neq2 30 27  60.5546  2.24276 1.49758  0.901878  0.894610\n\nThe covariance matrix of the residuals\n         eq1     eq2\neq1 24.30451 2.16943\neq2  2.16943 2.24276\n\nThe correlations of the residuals\n        eq1     eq2\neq1 1.00000 0.29384\neq2 0.29384 1.00000\n\n\n2SLS estimates for 'eq1' (equation 1)\nModel Formula: Q ~ P + PS + DI\nInstruments: ~PS + DI + PF\n\n             Estimate Std. Error  t value  Pr(>|t|)   \n(Intercept) -4.279471   5.543884 -0.77193 0.4471180   \nP           -0.374459   0.164752 -2.27287 0.0315350 * \nPS           1.296033   0.355193  3.64881 0.0011601 **\nDI           5.013977   2.283556  2.19569 0.0372352 * \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.92996 on 26 degrees of freedom\nNumber of observations: 30 Degrees of Freedom: 26 \nSSR: 631.917143 MSE: 24.304505 Root MSE: 4.92996 \nMultiple R-Squared: -0.02395 Adjusted R-Squared: -0.142098 \n\n\n2SLS estimates for 'eq2' (equation 2)\nModel Formula: Q ~ P + PF\nInstruments: ~PS + DI + PF\n\n              Estimate Std. Error  t value   Pr(>|t|)    \n(Intercept) 20.0328022  1.2231148  16.3785 1.5543e-15 ***\nP            0.3379816  0.0249196  13.5629 1.4344e-13 ***\nPF          -1.0009094  0.0825279 -12.1281 1.9456e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.497585 on 27 degrees of freedom\nNumber of observations: 30 Degrees of Freedom: 27 \nSSR: 60.554565 MSE: 2.242762 Root MSE: 1.497585 \nMultiple R-Squared: 0.901878 Adjusted R-Squared: 0.89461 \n```\n\n\n:::\n:::\n\n\n\n\n##\n\n### IV-2SLS Solution: tidy report (`symtemfit`)\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-8eafd9e63ac79ca6b588\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-8eafd9e63ac79ca6b588\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>IV 2SLS result(using `systemfit::systemfit()`<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],[\"eq1\",\"eq1\",\"eq1\",\"eq1\",\"eq2\",\"eq2\",\"eq2\"],[\"(Intercept)\",\"P\",\"PS\",\"DI\",\"(Intercept)\",\"P\",\"PF\"],[-4.279470614972329,-0.3744590609420762,1.296033242374322,5.013977078491189,20.03280215184291,0.3379815672232844,-1.000909374788582],[5.543884415318512,0.1647516960053911,0.3551931819125616,2.283555857918876,1.223114800306683,0.02491955805399323,0.08252794365223491],[-0.7719263776761949,-2.272869233041601,3.648812275606598,2.195688387084469,16.37851340431813,13.56290374375739,-12.12812691670014],[0.4471179846403324,0.03153504564071996,0.001160082326506995,0.03723523836604836,1.554312234475219e-15,1.434408147815702e-13,1.945554828353124e-12]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>eq<\\/th>\\n      <th>vars<\\/th>\\n      <th>Estimate<\\/th>\\n      <th>Std. Error<\\/th>\\n      <th>t value<\\/th>\\n      <th>Pr(&gt;|t|)<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":10,\"rownames\":false,\"columnDefs\":[{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"eq\",\"targets\":1},{\"name\":\"vars\",\"targets\":2},{\"name\":\"Estimate\",\"targets\":3},{\"name\":\"Std. Error\",\"targets\":4},{\"name\":\"t value\",\"targets\":5},{\"name\":\"Pr(>|t|)\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n##\n\n### Comparison (1/2): results of the reduced equations by OLS directly\n\n\nThe OLS regression results of **reduced price equation**:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{P}=&&-32.51&&+1.71PS_i&&+7.60DI_i\\\\ \n&(s)&&(7.9842)&&(0.3509)&&(1.7243)\\\\ \n&(t)&&(-4.07)&&(+4.87)&&(+4.41)\\\\ \n&(cont.)&&+1.35PF_i && &&\\\\ \n&(s)&&(0.2985) && &&\\\\ \n&(t)&&(+4.54) && &&\\\\ \n&(fit)&&R^2=0.8887&&\\bar{R}^2=0.8758 &&\\\\ \n&(Ftest)&&F^*=69.19&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\nThe OLS regression results of **reduced quantity equation**:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Q}=&&+7.90&&+0.66PS_i&&+2.17DI_i\\\\ \n&(s)&&(3.2434)&&(0.1425)&&(0.7005)\\\\ \n&(t)&&(+2.43)&&(+4.61)&&(+3.09)\\\\ \n&(cont.)&&-0.51PF_i && &&\\\\ \n&(s)&&(0.1213) && &&\\\\ \n&(t)&&(-4.18) && &&\\\\ \n&(fit)&&R^2=0.6974&&\\bar{R}^2=0.6625 &&\\\\ \n&(Ftest)&&F^*=19.97&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n\n##\n\n### Comparison (2/2): results of the structural equations by OLS directly\n\nWe can  apply OLS method directly. Of course estimation results will be biased.\n\n- tidy results of **bias** OLS estimation  for the demand equation:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Q}=&&+1.09&&+0.02P_i&&+0.71PS_i\\\\ \n&(s)&&(3.7116)&&(0.0768)&&(0.2143)\\\\ \n&(t)&&(+0.29)&&(+0.30)&&(+3.31)\\\\ \n&(cont.)&&+0.08DI_i && &&\\\\ \n&(s)&&(1.1909) && &&\\\\ \n&(t)&&(+0.06) && &&\\\\ \n&(fit)&&R^2=0.4957&&\\bar{R}^2=0.4375 &&\\\\ \n&(Ftest)&&F^*=8.52&&p=0.0004 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n- tidy results of **bias** OLS estimation for the supply equation:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{Q}=&&+20.03&&+0.34P_i&&-1.00PF_i\\\\ \n&(s)&&(1.2220)&&(0.0217)&&(0.0764)\\\\ \n&(t)&&(+16.39)&&(+15.54)&&(-13.10)\\\\ \n&(fit)&&R^2=0.9019&&\\bar{R}^2=0.8946 &&\\\\ \n&(Ftest)&&F^*=124.08&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n\n\n# 20.6 Cod supply and demand{#cod .monash-bg-blue .mcenter}\n\n\n## Cod supply and demand{.monash-bg-blue .mcenter .monash-bg-blue .mcenter}\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](pic/whiting-fishing.jpg){fig-align='center' width=130}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](pic/whiting-fishing2.jpg){fig-align='center' width=130}\n:::\n:::\n\n\n\n:::\n\n\n::: {.column width=\"40%\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](pic/whiting-fishing4.jpg){fig-align='center' width=97}\n:::\n:::\n\n\n\n:::\n\n::::\n\n\n##\n\n### Variables description\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-883336b28259d3d183f3\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-883336b28259d3d183f3\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Variables description of the cod case<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],[\"lprice\",\"lquan\",\"mon\",\"tue\",\"wen\",\"thu\",\"stormy\"],[\"the logarithmic market price of cod\",\"the logarithmic quantity of cod\",\"monday\",\"tuesday\",\"wensday\",\"thursday\",\"Stormy\"],[\"continuous variable\",\"continuous variable\",\"dummy variable 0/1\",\"dummy variable 0/1\",\"dummy variable 0/1\",\"dummy variable 0/1\",\"dummy variable 0/1\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>vars<\\/th>\\n      <th>label<\\/th>\\n      <th>note<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"tip\",\"pageLength\":8,\"rownames\":false,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"vars\",\"targets\":1},{\"name\":\"label\",\"targets\":2},{\"name\":\"note\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[8,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n::: {.notes}\n\nsource：Hill, R. C., W. E. Griffiths and G. C. Lim. Principles of Econometrics 4th Edition  [M], Wiley, 2011. chpt 11。reference：[PoE with R](https://bookdown.org/ccolonescu/RPoE4/simultaneous-equations-models.html)\n\n:::\n\n\n##\n\n### Sample data set\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-caf4d7d7358cdb61d1de\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-caf4d7d7358cdb61d1de\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Data set of cod case(obs. n=111)<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\",\"101\",\"102\",\"103\",\"104\",\"105\",\"106\",\"107\",\"108\",\"109\",\"110\",\"111\"],[\"1991-12-02\",\"1991-12-03\",\"1991-12-04\",\"1991-12-05\",\"1991-12-06\",\"1991-12-09\",\"1991-12-10\",\"1991-12-11\",\"1991-12-12\",\"1991-12-13\",\"1991-12-16\",\"1991-12-17\",\"1991-12-18\",\"1991-12-19\",\"1991-12-20\",\"1991-12-23\",\"1991-12-24\",\"1991-12-26\",\"1991-12-27\",\"1991-12-30\",\"1991-12-31\",\"1992-01-02\",\"1992-01-03\",\"1992-01-06\",\"1992-01-07\",\"1992-01-08\",\"1992-01-09\",\"1992-01-10\",\"1992-01-13\",\"1992-01-14\",\"1992-01-15\",\"1992-01-16\",\"1992-01-17\",\"1992-01-20\",\"1992-01-21\",\"1992-01-22\",\"1992-01-23\",\"1992-01-24\",\"1992-01-27\",\"1992-01-28\",\"1992-01-29\",\"1992-01-30\",\"1992-01-31\",\"1992-02-03\",\"1992-02-04\",\"1992-02-05\",\"1992-02-06\",\"1992-02-07\",\"1992-02-10\",\"1992-02-11\",\"1992-02-12\",\"1992-02-13\",\"1992-02-14\",\"1992-02-18\",\"1992-02-19\",\"1992-02-20\",\"1992-02-21\",\"1992-02-24\",\"1992-02-25\",\"1992-02-26\",\"1992-02-27\",\"1992-02-28\",\"1992-03-02\",\"1992-03-03\",\"1992-03-04\",\"1992-03-05\",\"1992-03-06\",\"1992-03-09\",\"1992-03-10\",\"1992-03-11\",\"1992-03-12\",\"1992-03-13\",\"1992-03-16\",\"1992-03-17\",\"1992-03-18\",\"1992-03-19\",\"1992-03-20\",\"1992-03-23\",\"1992-03-24\",\"1992-03-25\",\"1992-03-26\",\"1992-03-27\",\"1992-03-30\",\"1992-03-31\",\"1992-04-01\",\"1992-04-02\",\"1992-04-03\",\"1992-04-06\",\"1992-04-07\",\"1992-04-08\",\"1992-04-09\",\"1992-04-10\",\"1992-04-13\",\"1992-04-14\",\"1992-04-15\",\"1992-04-16\",\"1992-04-17\",\"1992-04-21\",\"1992-04-22\",\"1992-04-23\",\"1992-04-24\",\"1992-04-27\",\"1992-04-28\",\"1992-04-29\",\"1992-04-30\",\"1992-05-01\",\"1992-05-04\",\"1992-05-05\",\"1992-05-06\",\"1992-05-07\",\"1992-05-08\"],[-0.4307829,0,0.0723207,0.247139,0.6643268,-0.2065143,-0.1158318,-0.2598674,-0.1171254,-0.3420761,-0.1255632,0.027399,-0.0712275,0.1230601,0.2130932,-0.3172045,-0.1088388,0.2231435,0.2464593,-0.075431,0.2055992,0.2188098,0.307025,0.399592,0.4969802,0.3968258,0.2830518,0.2263384,-0.0723207,-0.1545295,0.2363888,0.1718503,0.1541506,0.0350913,0.218131,-0.0624355,-0.4418328,-0.7699343,-0.7391911,-0.7230001,-0.5184302,-0.5533853,-0.5590724,-0.4238143,-0.7731899,-0.2040953,0.3841877,0.3479887,0.3229889,0.4345259,0.2000211,-0.0071685,-0.4744579,-0.7711087,-1.094774,-0.8602012,-0.597837,-0.567984,-0.7711087,-0.2724146,0.1849223,0.20676,0.07410799999999999,-0.0071685,-0.2548923,-0.2364898,-0.4848501,-0.8119307,-0.4780358,-0.2301122,-0.2887938,-0.3409266,-0.4812668,-0.5817336,-0.0370413,0.0746435,-0.5268259,-0.1123292,-0.2376716,-0.4243931,-0.4828126,-0.1923718,0.1823216,0.2876821,-0.1873341,-0.4404448,-0.567984,-0.3873608,-0.5108256,-0.6149098,-0.3876929,-0.3716677,-0.3101549,-0.3502024,-0.2231435,-0.3119048,-0.2258646,-0.2842691,-0.09716379999999999,-0.1419181,-0.5364382,-0.4596867,-0.4866114,-0.7603559,-0.8931236,-1.107745,-0.7985078,-0.0870114,0.1849223,0.2231435,0.5611184],[8058.003,2224.001,4231.001,5749.998,2551.001,10952,7485,9008.995999999999,4055,9992.003000000001,5180.002,5030,7083,9762.995999999999,5999.002,12196,3463.999,814.9999,6626.999,14260.01,4014.999,4109.001,7221.997,11344,3370.001,3470,13607.01,5260,11930,5590,2269.999,4690,1283,579.9999,1500.001,4410.001,9783.995999999999,11140,4288.999,5548.001,3445,6067.998,4525,8249.996999999999,1860.001,1279.999,4855,7939.001,6274.992,2680,5389.999,8399.999,13708,17555,3493.998,5869.997,8390,4339.999,2100.001,2575,2849.999,6189.998,5615,6610,8054.999,10135,5263.001,21619.99,9625,3349.999,10315,3030.001,15460,9589.999,1704.999,5510,7346.999,2585,3745.001,2940,12040,2235.001,2220.001,1112.001,4880.001,11310,14455,7907.001,1464.999,12280,6249.998,5350.002,5755.007,1609.999,490.0003,9774.995999999999,6499.999,10520,3999.999,6230.003,15550.01,5180.002,3509.999,5785.002,8950.003000000001,8219.996999999999,5490,1289.999,1574.999,6400,4140],[8.994421000000001,7.707063,8.350194,8.656955,7.844241,9.301277000000001,8.920655999999999,9.105979,8.307706,9.209540000000001,8.552561000000001,8.523175,8.865453,9.186355000000001,8.699348000000001,9.408863,8.150179,6.703188,8.798907,9.565213999999999,8.297791999999999,8.320935,8.884887000000001,9.336444,8.122668000000001,8.151910000000001,9.51834,8.567886,9.386811,8.628735000000001,7.727535,8.453188000000001,7.156956,6.363028,7.313221,8.391629999999999,9.188503000000001,9.318296999999999,8.363809,8.621193,8.144679,8.710784,8.417373,9.017968,7.528332,7.154615,8.487764,8.979543,8.744327999999999,7.893572,8.5923,9.035987,9.525734999999999,9.773094,8.158802,8.677609,9.034796,8.375629,7.649693,7.853605,7.955074,8.730689999999999,8.633196999999999,8.796339,8.994047999999999,9.223750000000001,8.568457,9.981374000000001,9.172119,8.116714999999999,9.241353999999999,8.016318,9.646011,9.168476,7.44132,8.614319999999999,8.902047,7.857481,8.228177000000001,7.986165,9.395989,7.711997,7.705263,7.013916,8.492901,9.333443000000001,9.578795,8.975504000000001,7.28961,9.415728,8.740335999999999,8.584852,8.657825000000001,7.383989,6.194406,9.187583,8.779557,9.261032999999999,8.294048999999999,8.737132000000001,9.651816,8.552561000000001,8.163371,8.663024,9.099409,9.014324999999999,8.610683,7.162397,7.36201,8.764053000000001,8.328450999999999],[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0],[0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0],[0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0],[0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0],[1,1,0,1,1,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>date<\\/th>\\n      <th>lprice<\\/th>\\n      <th>quan<\\/th>\\n      <th>lquan<\\/th>\\n      <th>mon<\\/th>\\n      <th>tue<\\/th>\\n      <th>wed<\\/th>\\n      <th>thu<\\/th>\\n      <th>stormy<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"tip\",\"pageLength\":7,\"rownames\":false,\"columnDefs\":[{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"date\",\"targets\":1},{\"name\":\"lprice\",\"targets\":2},{\"name\":\"quan\",\"targets\":3},{\"name\":\"lquan\",\"targets\":4},{\"name\":\"mon\",\"targets\":5},{\"name\":\"tue\",\"targets\":6},{\"name\":\"wed\",\"targets\":7},{\"name\":\"thu\",\"targets\":8},{\"name\":\"stormy\",\"targets\":9}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[7,10,25,50,100]}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n##\n\n### Scatter\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/lecture-20-sem-estimation.rmarkdown/unnamed-chunk-55-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n##\n\n### The structural and reduced SEM\n\nGiven the structural SEM:\n\n$$\n\\begin{cases}\n\\begin{align}\nlquan_t &= \\alpha_0+\\alpha_1lprice_t+\\alpha_2mon_t+\\alpha_3tue_t+\\alpha_4wen_t+\\alpha_5thu_t+u_{1t}  &&\\text{(demand eq)}\\\\\nlquan_t &= \\beta_0+\\beta_1lprice_t+\\beta_3stormy_t+u_{2t}    &&\\text{(supply eq)}\n\\end{align}\n\\end{cases}\n$$\n\nWe can obtain the reduced SEM:\n\n$$\n\\begin{cases}\n\\begin{align}\nlquan_t &= \\pi_0 + \\pi_1mon_t+\\pi_2tue_t+\\pi_3wen_t+\\pi_4thu_t\n+\\pi_5stormy_t+v_t &&\\text{(reduced eq1)}\\\\\nlprice_t &= \\pi_0 + \\pi_1mon_t+\\pi_2tue_t+\\pi_3wen_t+\\pi_4thu_t\n+\\pi_5stormy_t+v_t &&\\text{(reduced eq2)}\\\\\n\\end{align}\n\\end{cases}\n$$\n\n::: {.notes}\ndisplay\n:::\n\n\n##\n\n### OLS regression results of the reduced SEM\n\n\nThe regression results of reduced **quantity** equation show as follows:\n\n$$\n\\begin{alignedat}{999}\n&\\widehat{lquan}=&&+8.81&&+0.10mon&&-0.48tue&&-0.55wed&&+0.05thu&&-0.39stormy\\\\\n&\\text{(t)}&&(59.9225)&&(0.4891)&&(-2.4097)&&(-2.6875)&&(0.2671)&&(-2.6979)\\\\\n&\\text{(se)}&&(0.1470)&&(0.2065)&&(0.2011)&&(0.2058)&&(0.2010)&&(0.1437)\\\\\n&\\text{(fitness)}&& n=111;&& R^2=0.1934;&& \\bar{R^2}=0.1550\\\\\n& && F^{\\ast}=5.03;&& p=0.0004\\\\\n\\end{alignedat}\n$$\n\nThe regression results of reduced **price** equation show as follows:\n\n$$\n\\begin{alignedat}{999}\n&\\widehat{lprice}=&&-0.27&&-0.11mon&&-0.04tue&&-0.01wed&&+0.05thu&&+0.35stormy\\\\\n&\\text{(t)}&&(-3.5569)&&(-1.0525)&&(-0.3937)&&(-0.1106)&&(0.4753)&&(4.6387)\\\\\n&\\text{(se)}&&(0.0764)&&(0.1073)&&(0.1045)&&(0.1069)&&(0.1045)&&(0.0747)\\\\\n&\\text{(fitness)}&& n=111;&& R^2=0.1789;&& \\bar{R^2}=0.1398\\\\\n& && F^{\\ast}=4.58;&& p=0.0008\n\\end{alignedat}\n$$\n\n::: {.notes}\nwhy\n:::\n\n##\n\n### IV-2SLS regression results: R code\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# set equation systems\nfish.D <- formula(lquan ~ lprice + mon + tue + wed + thu)\nfish.S <- formula(lprice ~ lquan + stormy)\nfish.eqs <- list(fish.D, fish.S)\n# set instruments\nfish.ivs <- ~ mon + tue + wed + thu + stormy\n# system fit using `2SLS` method\nfish.sys <- systemfit(fish.eqs,\n  method = \"2SLS\",\n  inst = fish.ivs, data = fultonfish\n)\n# estimation summary\nfish.smry <- summary(fish.sys)\n```\n:::\n\n\n\n\n##\n\n### IV-2SLS regression results: raw report\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nsystemfit results \nmethod: 2SLS \n\n         N  DF    SSR  detRCov   OLS-R2 McElroy-R2\nsystem 222 213 65.577 0.055061 0.143396   0.308369\n\n      N  DF     SSR      MSE     RMSE       R2   Adj R2\neq1 111 105 52.0903 0.496098 0.704342 0.139124 0.098130\neq2 111 108 13.4867 0.124877 0.353379 0.159506 0.143941\n\nThe covariance matrix of the residuals\n          eq1       eq2\neq1 0.4960983 0.0830042\neq2 0.0830042 0.1248767\n\nThe correlations of the residuals\n         eq1      eq2\neq1 1.000000 0.333484\neq2 0.333484 1.000000\n\n\n2SLS estimates for 'eq1' (equation 1)\nModel Formula: lquan ~ lprice + mon + tue + wed + thu\nInstruments: ~mon + tue + wed + thu + stormy\n\n              Estimate Std. Error  t value   Pr(>|t|)    \n(Intercept)  8.5059113  0.1661669 51.18896 < 2.22e-16 ***\nlprice      -1.1194169  0.4286450 -2.61152  0.0103334 *  \nmon         -0.0254022  0.2147742 -0.11827  0.9060766    \ntue         -0.5307694  0.2080001 -2.55177  0.0121574 *  \nwed         -0.5663511  0.2127549 -2.66199  0.0089895 ** \nthu          0.1092673  0.2087866  0.52334  0.6018373    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.704342 on 105 degrees of freedom\nNumber of observations: 111 Degrees of Freedom: 105 \nSSR: 52.090321 MSE: 0.496098 Root MSE: 0.704342 \nMultiple R-Squared: 0.139124 Adjusted R-Squared: 0.09813 \n\n\n2SLS estimates for 'eq2' (equation 2)\nModel Formula: lprice ~ lquan + stormy\nInstruments: ~mon + tue + wed + thu + stormy\n\n                Estimate   Std. Error  t value   Pr(>|t|)    \n(Intercept) -2.90660e-01  1.03438e+00 -0.28100 0.77924840    \nlquan        3.78095e-05  1.19797e-01  0.00032 0.99974876    \nstormy       3.35276e-01  8.58664e-02  3.90463 0.00016468 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.353379 on 108 degrees of freedom\nNumber of observations: 111 Degrees of Freedom: 108 \nSSR: 13.486684 MSE: 0.124877 Root MSE: 0.353379 \nMultiple R-Squared: 0.159506 Adjusted R-Squared: 0.143941 \n```\n\n\n:::\n:::\n\n\n\n\n\n##\n\n### IV-2SLS regression results: tidy report\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-3a55715b3a73598e6f9f\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3a55715b3a73598e6f9f\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Results of 2SLS with error corrrection<\\/caption>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\"],[\"eq1\",\"eq1\",\"eq1\",\"eq1\",\"eq1\",\"eq1\",\"eq2\",\"eq2\",\"eq2\"],[\"(Intercept)\",\"lprice\",\"mon\",\"tue\",\"wed\",\"thu\",\"(Intercept)\",\"lquan\",\"stormy\"],[8.505911289050198,-1.119416947039972,-0.02540216463762434,-0.5307693846836241,-0.5663510748224602,0.1092673145001125,-0.2906595566467119,3.780953850157642e-05,0.3352760455400715],[0.1661668938940059,0.4286450308690112,0.2147741537203133,0.2080000767457944,0.2127548551167537,0.2087865779066188,1.034377422556216,0.1197968748807406,0.0858663712397227],[51.18896483962639,-2.611524376639869,-0.1182738434658388,-2.551774946373214,-2.661988956781566,0.5233445348626913,-0.2809995174956704,0.000315613729817379,3.904625765586903],[0,0.01033344707849881,0.9060766496196262,0.01215742398756126,0.008989487357948356,0.6018372636438394,0.7792483979537319,0.999748758923898,0.0001646795269154566]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>eq<\\/th>\\n      <th>vars<\\/th>\\n      <th>Estimate<\\/th>\\n      <th>Std. Error<\\/th>\\n      <th>t value<\\/th>\\n      <th>Pr(&gt;|t|)<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":10,\"rownames\":false,\"columnDefs\":[{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"visible\":false,\"targets\":0},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"eq\",\"targets\":1},{\"name\":\"vars\",\"targets\":2},{\"name\":\"Estimate\",\"targets\":3},{\"name\":\"Std. Error\",\"targets\":4},{\"name\":\"t value\",\"targets\":5},{\"name\":\"Pr(>|t|)\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n##\n\n### Comparison with the biased OLS estimation: R code\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# demand equation\nfish.D <- formula(lquan ~ lprice + mon + tue + wed + thu)\nols_fish_D <- lm(fish.D, data = fultonfish)\n\n# supply equation\nfish.S <- formula(lprice ~ lquan + stormy)\nols_fish_S <- lm(fish.S, data = fultonfish)\n```\n:::\n\n\n\n\n##\n\n### Comparison with the biased OLS estimation: raw report\n\n- raw R summry of **bias** OLS estimation for the demand equation:\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = fish.D, data = fultonfish)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.23844 -0.36737  0.08832  0.42304  1.24866 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  8.60689    0.14304  60.170  < 2e-16 ***\nlprice      -0.56255    0.16821  -3.344  0.00114 ** \nmon          0.01432    0.20265   0.071  0.94381    \ntue         -0.51624    0.19769  -2.611  0.01034 *  \nwed         -0.55537    0.20232  -2.745  0.00712 ** \nthu          0.08162    0.19782   0.413  0.68073    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6702 on 105 degrees of freedom\nMultiple R-squared:  0.2205,\tAdjusted R-squared:  0.1834 \nF-statistic:  5.94 on 5 and 105 DF,  p-value: 7.08e-05\n```\n\n\n:::\n:::\n\n\n\n\n##\n\n### Comparison with the biased OLS estimation: stylized results\n\n- tidy results of **bias** OLS estimation  for the demand equation:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{lquan}=&&+8.61&&-0.56lprice_i&&+0.01mon_i\\\\ \n&(s)&&(0.1430)&&(0.1682)&&(0.2026)\\\\ \n&(t)&&(+60.17)&&(-3.34)&&(+0.07)\\\\ \n&(cont.)&&-0.52tue_i&&-0.56wed_i&&+0.08thu_i\\\\ \n&(s)&&(0.1977)&&(0.2023)&&(0.1978)\\\\ \n&(t)&&(-2.61)&&(-2.75)&&(+0.41)\\\\ \n&(fit)&&R^2=0.2205&&\\bar{R}^2=0.1834 &&\\\\ \n&(Ftest)&&F^*=5.94&&p=0.0001 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n- tidy results of **bias** OLS estimation  for the supply equation:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n$$\n\\begin{alignedat}{999}\n\\begin{split}\n&\\widehat{lprice}=&&+0.60&&-0.10lquan_i&&+0.30stormy_i\\\\ \n&(s)&&(0.3948)&&(0.0455)&&(0.0742)\\\\ \n&(t)&&(+1.51)&&(-2.26)&&(+4.01)\\\\ \n&(fit)&&R^2=0.1974&&\\bar{R}^2=0.1825 &&\\\\ \n&(Ftest)&&F^*=13.28&&p=0.0000 &&\n\\end{split}\n\\end{alignedat}\n$$\n:::\n\n\n\n\n\n\n\n##\n\n### Comparison: the biased OLS estimation\n\n- raw R summry of **bias** OLS estimation for the supply equation:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = fish.S, data = fultonfish)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.89381 -0.21934  0.00898  0.20711  0.82067 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.59605    0.39481   1.510  0.13404    \nlquan       -0.10273    0.04554  -2.256  0.02608 *  \nstormy       0.29798    0.07422   4.015  0.00011 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3453 on 108 degrees of freedom\nMultiple R-squared:  0.1974,\tAdjusted R-squared:  0.1825 \nF-statistic: 13.28 on 2 and 108 DF,  p-value: 6.985e-06\n```\n\n\n:::\n:::\n\n\n\n\n\n\n# 20.7 Exercise and computation{#exercise .monash-bg-blue .mcenter}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n## Labor market of married Working Women\n\n<!-- insert image here -->\n\n##\n\n### Story background\n\nLet's consider the labor market for married women already in the workforce.\n\nWe will use the data on working, married women in `wooldridge::mroz` to estimate the labor supply and wage demand equations by 2SLS.\n\nThe full set of instruments includes `educ`, `age`, `kidslt6`, `nwifeinc`, `exper`, and `exper2`.\n\n::: {.aside}\nPlease follow our accompany course repository at <https://github.com/huhuaping/course-emiii-accompany> or <https://gitee.com/kevinhhp/course-emiii-accompany>.\n:::\n\n\n##\n\n### Variables and definition\n\nWe will focus on the following variables.\n\n\n- `lwage`: log(wage)\n\n- `hours`: hours worked, 1975\n\n- `kidslt6`: kids less than  6 years\n\n- `age`: woman's age in yrs\n\n- `educ`: years of schooling\n\n- `exper`: actual labor mkt exper\n\n- `expersq`: exper^2\n\n- `nwifeinc`: (faminc - wage*hours)/1000\n\n\n\n\n##\n\n### SEM setting: the structrual equations\n\n$$\n\\begin{aligned}\n\\text { hours } & =\\alpha_1 \\log ( wage)+\\beta_{10}+\\beta_{11} { educ }+\\beta_{12} age+\\beta_{13}  { kidslt6 } &&\\\\\n&+\\beta_{14} { nwifeinc }+u_1  &&\\text{(supply)}\\\\\n\\log ({ wage }) &=\\alpha_2 { hours }+\\beta_{20}+\\beta_{21} { educ }+\\beta_{22} { exper }  +\\beta_{23} { exper }^2+ u_2 && \\quad \\text{(demand)}\n\\end{aligned}\n$$\n\n- In the demand function, we write the wage offer as a function of hours and the usual productivity variables.\n\n- All variables except `hours` and `log(wage)` are assumed to be exogenous.\n\n- `educ` might be correlated with omitted `ability` in either equation. Here, we just ignore the omitted ability problem.\n\n\n##\n\n### SEM setting: the reduced equations\n\n$$\n\\begin{alignedat}{8}\n\\text { hours } & =\\pi_{10}+\\pi_{11} { educ }+\\pi_{12} age+\\pi_{13}  { kidslt6 }  +\\pi_{14} { nwifeinc }\\\\\n&+\\pi_{15} { exper }  +\\pi_{16} {exper}^2 +v_1  \\\\\n\\log ({ wage }) &=\\pi_{20}+\\pi_{21} { educ }+\\pi_{22} age+\\pi_{23}  { kidslt6 }  +\\pi_{24} { nwifeinc } \\\\\n&+\\pi_{25} { exper }  +\\pi_{26} {exper}^2+ v_2\n\\end{alignedat}\n$$\n\n\n##\n\n### Exercise tasks 1/2: system fit with TSLS\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nsystemfit results \nmethod: 2SLS \n\n         N  DF       SSR detRCov   OLS-R2 McElroy-R2\nsystem 856 845 773893318  155089 -2.00762   0.748802\n\n      N  DF         SSR         MSE        RMSE        R2    Adj R2\neq1 428 423 1.95266e+02 4.61621e-01    0.679427  0.125654  0.117385\neq2 428 422 7.73893e+08 1.83387e+06 1354.204549 -2.007617 -2.043253\n\nThe covariance matrix of the residuals\n            eq1         eq2\neq1    0.461621    -831.543\neq2 -831.542683 1833869.960\n\nThe correlations of the residuals\n          eq1       eq2\neq1  1.000000 -0.903769\neq2 -0.903769  1.000000\n\n\n2SLS estimates for 'eq1' (equation 1)\nModel Formula: lwage ~ hours + educ + exper + expersq\nInstruments: ~age + kidslt6 + nwifeinc + educ + exper + expersq\n\n                Estimate   Std. Error  t value   Pr(>|t|)    \n(Intercept) -0.655725423  0.337788290 -1.94123   0.052894 .  \nhours        0.000125900  0.000254611  0.49448   0.621223    \neduc         0.110330004  0.015524358  7.10690 5.0768e-12 ***\nexper        0.034582356  0.019491555  1.77422   0.076746 .  \nexpersq     -0.000705769  0.000454080 -1.55428   0.120865    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.679427 on 423 degrees of freedom\nNumber of observations: 428 Degrees of Freedom: 423 \nSSR: 195.265558 MSE: 0.461621 Root MSE: 0.679427 \nMultiple R-Squared: 0.125654 Adjusted R-Squared: 0.117385 \n\n\n2SLS estimates for 'eq2' (equation 2)\nModel Formula: hours ~ lwage + educ + age + kidslt6 + nwifeinc\nInstruments: ~age + kidslt6 + nwifeinc + educ + exper + expersq\n\n              Estimate Std. Error  t value   Pr(>|t|)    \n(Intercept) 2225.66187  574.56413  3.87365 0.00012424 ***\nlwage       1639.55563  470.57569  3.48415 0.00054535 ***\neduc        -183.75128   59.09981 -3.10917 0.00200323 ** \nage           -7.80609    9.37801 -0.83238 0.40566400    \nkidslt6     -198.15431  182.92914 -1.08323 0.27932494    \nnwifeinc     -10.16959    6.61474 -1.53741 0.12494168    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1354.204549 on 422 degrees of freedom\nNumber of observations: 428 Degrees of Freedom: 422 \nSSR: 773893123.12815 MSE: 1833869.960019 Root MSE: 1354.204549 \nMultiple R-Squared: -2.007617 Adjusted R-Squared: -2.043253 \n```\n\n\n:::\n:::\n\n\n\n\n\n##\n\n### Exercise tasks 2/2: OLS estimator and several tests\n\nSo we should conduct OLS estimation and several tests as we have learned.\n\n- Conduct OLS estimation directly for each structural equation.\n\n- Weak instrument test (Restricted F test or Cragg-donald test).\n\n- Instrument Exogeneity test (J-test).\n\n- Regressor Endogeneity test (Wu-Hausman test).\n\nFind these results and get the conclusion!\n\n\n## End Of This Chapter{.center-h background-color=\"aliceblue\"  background-image=\"pic/thank-you-gif-funny-little-yellow.gif\" background-size=\"600px\"  background-position=\"center\" background-opacity=\"0.8\" style=\"font-size:75px !important\"}\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}